<a href="https://colab.research.google.com/github/Kristina-aut/For-example-Task-_dataset_studets/blob/main/First_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
rng = np.random.default_rng(3)
X = rng.standard_normal((10, 3))

    # array([[ 0.22578661, -0.35263079, -0.28128742],
    #        [-0.66804635, -1.05515055, -0.39080098],
    #        [ 0.48194539, -0.23855361,  0.9577587 ],
    #        [-0.19980213,  0.02425957,  1.54582085],
    #        [ 0.54510552, -0.50522874, -0.18283897],
    #        [ 0.54052513,  1.93508803, -0.26962033],
    #        [-0.24355868,  1.0023136 , -0.88645994],
    #        [-0.29172023,  0.88253897,  0.58035002],
    #        [ 0.0915167 ,  0.67010435, -2.82816231],
    #        [ 1.02130682, -0.95964476, -1.66861984]])

X.mean(axis=0)

    # array([ 0.15030588,  0.14030961, -0.34238602])

array([ 0.41551948, -0.25582912,  0.01473861])

In [ ]:
56/100, (1+56)/67, 3-5/45, 35/5/7

(0.56, 0.8507462686567164, 2.888888888888889, 1.0)

In [ ]:
(15600*0.09+15600)*0.16+(15600*0.09+15600)

19724.64

In [ ]:
df=pd.read_csv('/content/students.csv', delimiter=',')

delimiter=',' разделитель в данных

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          186 non-null    int64
 1   Growth                       186 non-null    int64
 2   Shoe size                    186 non-null    int64
 3   Course number                186 non-null    int64
 4   Year of birth                186 non-null    int64
 5   Friend number                186 non-null    int64
 6   Russian rating               186 non-null    int64
 7   Maths rating                 186 non-null    int64
 8   Physics rating               186 non-null    int64
 9   Computer science rating      186 non-null    int64
 10  Chemistry rating             186 non-null    int64
 11  Literature rating            186 non-null    int64
 12  History rating               186 non-null    int64
 13  Geography rating             186 non-null    int64
 14  Biology rating               186 non-null    int64
 15  Foreign language rating      186 non-null    int64
 16  Social science rating        186 non-null    int64
 17  Distance to home km          186 non-null    int64
 18  Minutes to first class       186 non-null    int64
 19  Children number              150 non-null    float64
 20  Removed teeth                148 non-null    float64
 21  Weight                       157 non-null    float64
 22  Glasses                      184 non-null    object
 23  Sex                          186 non-null    object
 24  Problems in last semester    186 non-null    object
 25  Coin                         186 non-null    object
 26  Rock paper scissors          186 non-null    object
 27  Animal                       186 non-null    object
 28  Month of birthday            186 non-null    int64
 29  Your rating in university    186 non-null    object
 30  Fastfood                     186 non-null    object
 31  Height of 5000 mm            186 non-null    int64
 32  Width of 5000 mm             186 non-null    int64
 33  Putin age                    186 non-null    int64
 34  Army                         186 non-null    object
 35  Hostel                       186 non-null    object
 36  Hair length                  186 non-null    float64
 37  Floor number                 186 non-null    int64
 38  Social network duration min  186 non-null    int64
 39  Chocolate                    186 non-null    object
 40  City population              186 non-null    float64
 41  Strange people               186 non-null    object
 42  Your insitute                186 non-null    object
 43  Brother-sister               186 non-null    object
 44  Plane seat                   186 non-null    object
 45  MIddle and index finger      186 non-null    int64
 46  Middle and ring finger       186 non-null    float64
 47  Middle and little finger     186 non-null    float64
dtypes: float64(7), int64(26), object(15)
memory usage: 69.9+ KB

In [ ]:
df.shape

(186, 48)

In [ ]:
df

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
0,20,170,40,2,2002,100,85,86,0,84,...,45,Сникерс,800000.0,Экономический,Математический и ИТ,нет ни брата ни сестры,У окна (пардон: у иллюминатора),20,10.0,40.0
1,22,191,43,7,2000,307,69,74,64,72,...,180,КитКат,800000.0,Математический и ИТ,Математический и ИТ,есть и брат и сестра,В середине,5,5.0,20.0
2,21,172,41,4,2000,186,78,62,0,0,...,90,КитКат,770000.0,Педагогический,Другое,есть брат,У окна (пардон: у иллюминатора),13,10.0,26.0
3,19,168,38,2,2003,604,72,0,0,0,...,200,Баунти,900000.0,СоцГум,Юридический,есть сестра,У окна (пардон: у иллюминатора),12,13.5,35.0
4,23,159,36,1,1998,144,0,0,0,0,...,400,Баунти,860000.0,Педагогический,Педагогический,есть сестра,У окна (пардон: у иллюминатора),10,11.0,22.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181,23,168,39,7,1999,228,93,68,0,0,...,300,Твикс,770000.0,Естественный (биология-химия-физика-технари),Естественный (биология-химия-физика-технари),нет ни брата ни сестры,У окна (пардон: у иллюминатора),13,23.0,45.0
182,19,169,38,1,2003,0,73,5,0,0,...,75,M&Ms,1250000.0,Педагогический,СоцГум,есть сестра,У окна (пардон: у иллюминатора),8,9.0,15.0
183,18,161,37,2,2003,11,98,0,0,0,...,460,Твикс,1000000.0,Естественный (биология-химия-физика-технари),Другое,есть и брат и сестра,У окна (пардон: у иллюминатора),9,16.0,35.0
184,19,169,41,1,2003,22,82,86,0,0,...,540,Твикс,850000.0,Естественный (биология-химия-физика-технари),Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),9,15.0,25.0
185,18,164,39,2,2003,500,94,5,0,0,...,400,Твикс,800000.0,Юридический,СоцГум,нет ни брата ни сестры,У окна (пардон: у иллюминатора),7,10.0,35.0

In [ ]:
df.head()

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
0,20,170,40,2,2002,100,85,86,0,84,...,45,Сникерс,800000.0,Экономический,Математический и ИТ,нет ни брата ни сестры,У окна (пардон: у иллюминатора),20,10.0,40.0
1,22,191,43,7,2000,307,69,74,64,72,...,180,КитКат,800000.0,Математический и ИТ,Математический и ИТ,есть и брат и сестра,В середине,5,5.0,20.0
2,21,172,41,4,2000,186,78,62,0,0,...,90,КитКат,770000.0,Педагогический,Другое,есть брат,У окна (пардон: у иллюминатора),13,10.0,26.0
3,19,168,38,2,2003,604,72,0,0,0,...,200,Баунти,900000.0,СоцГум,Юридический,есть сестра,У окна (пардон: у иллюминатора),12,13.5,35.0
4,23,159,36,1,1998,144,0,0,0,0,...,400,Баунти,860000.0,Педагогический,Педагогический,есть сестра,У окна (пардон: у иллюминатора),10,11.0,22.0

In [ ]:
df.tail(18)

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
168,22,161,38,7,2000,50,91,74,0,0,...,1800,Натс,850000.0,Математический и ИТ,Другое,есть брат,У окна (пардон: у иллюминатора),5,13.0,35.0
169,21,160,37,4,2001,221,94,76,0,0,...,0,Сникерс,800000.0,Педагогический,Экономический,нет ни брата ни сестры,У окна (пардон: у иллюминатора),9,10.0,32.0
170,22,168,38,4,2000,49,100,56,0,0,...,240,КитКат,500000.0,Педагогический,Экономический,нет ни брата ни сестры,У окна (пардон: у иллюминатора),10,5.0,20.0
171,20,162,37,2,2002,70,82,0,0,0,...,540,Твикс,900.0,СоцГум,Юридический,есть сестра,У прохода,4,11.0,25.0
172,21,164,37,4,2000,260,86,0,0,0,...,60,Милки Вей,900000.0,Математический и ИТ,СоцГум,есть брат,У окна (пардон: у иллюминатора),10,6.0,30.0
173,29,176,39,7,1992,233,72,69,0,0,...,60,Сникерс,850000.0,Математический и ИТ,Экономический,есть сестра,У окна (пардон: у иллюминатора),7,11.0,30.0
174,20,158,37,3,2001,21,91,56,0,0,...,120,Милки Вей,700000.0,Математический и ИТ,Естественный (биология-химия-физика-технари),нет ни брата ни сестры,У прохода,9,10.0,35.0
175,18,176,38,2,2003,183,90,0,0,0,...,240,Марс,854627.0,Естественный (биология-химия-физика-технари),СоцГум,есть сестра,У окна (пардон: у иллюминатора),16,13.0,28.0
176,21,162,38,7,2000,150,89,0,0,0,...,300,Твикс,800000.0,СоцГум,СоцГум,есть и брат и сестра,У окна (пардон: у иллюминатора),13,12.0,40.0
177,23,155,36,6,1999,90,91,51,0,0,...,100,Баунти,900000.0,Математический и ИТ,Математический и ИТ,есть сестра,У окна (пардон: у иллюминатора),5,4.0,3.0
178,21,170,39,4,2001,123,76,0,0,0,...,360,Сникерс,800000.0,СоцГум,Юридический,есть и брат и сестра,У окна (пардон: у иллюминатора),3,2.0,7.0
179,20,176,42,3,2001,80,85,0,0,0,...,120,Сникерс,700000.0,СоцГум,Юридический,есть сестра,У окна (пардон: у иллюминатора),5,5.0,20.0
180,21,167,36,4,2000,120,98,56,0,0,...,120,Твикс,8000000.0,Педагогический,Педагогический,есть сестра,У окна (пардон: у иллюминатора),10,5.0,25.0
181,23,168,39,7,1999,228,93,68,0,0,...,300,Твикс,770000.0,Естественный (биология-химия-физика-технари),Естественный (биология-химия-физика-технари),нет ни брата ни сестры,У окна (пардон: у иллюминатора),13,23.0,45.0
182,19,169,38,1,2003,0,73,5,0,0,...,75,M&Ms,1250000.0,Педагогический,СоцГум,есть сестра,У окна (пардон: у иллюминатора),8,9.0,15.0
183,18,161,37,2,2003,11,98,0,0,0,...,460,Твикс,1000000.0,Естественный (биология-химия-физика-технари),Другое,есть и брат и сестра,У окна (пардон: у иллюминатора),9,16.0,35.0
184,19,169,41,1,2003,22,82,86,0,0,...,540,Твикс,850000.0,Естественный (биология-химия-физика-технари),Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),9,15.0,25.0
185,18,164,39,2,2003,500,94,5,0,0,...,400,Твикс,800000.0,Юридический,СоцГум,нет ни брата ни сестры,У окна (пардон: у иллюминатора),7,10.0,35.0

In [ ]:
df.head(13)

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
0,20,170,40,2,2002,100,85,86,0,84,...,45,Сникерс,800000.0,Экономический,Математический и ИТ,нет ни брата ни сестры,У окна (пардон: у иллюминатора),20,10.0,40.0
1,22,191,43,7,2000,307,69,74,64,72,...,180,КитКат,800000.0,Математический и ИТ,Математический и ИТ,есть и брат и сестра,В середине,5,5.0,20.0
2,21,172,41,4,2000,186,78,62,0,0,...,90,КитКат,770000.0,Педагогический,Другое,есть брат,У окна (пардон: у иллюминатора),13,10.0,26.0
3,19,168,38,2,2003,604,72,0,0,0,...,200,Баунти,900000.0,СоцГум,Юридический,есть сестра,У окна (пардон: у иллюминатора),12,13.5,35.0
4,23,159,36,1,1998,144,0,0,0,0,...,400,Баунти,860000.0,Педагогический,Педагогический,есть сестра,У окна (пардон: у иллюминатора),10,11.0,22.0
5,18,177,40,2,2003,100,70,68,0,75,...,250,Сникерс,1200000.0,СоцГум,Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),12,7.0,30.0
6,18,180,42,0,2004,0,66,4,0,0,...,30,Сникерс,700000.0,Педагогический,Юридический,есть брат,У окна (пардон: у иллюминатора),5,30.0,35.0
7,19,180,48,1,2003,5,72,0,0,0,...,240,Баунти,880000.0,Естественный (биология-химия-физика-технари),Юридический,есть брат,У окна (пардон: у иллюминатора),7,5.0,25.0
8,20,185,46,3,2002,28,87,76,0,0,...,120,Скиттлс (хотя это и не шоколадка),800000.0,Естественный (биология-химия-физика-технари),Экономический,есть брат,В середине,5,3.0,15.0
9,22,168,38,6,2000,297,71,5,0,0,...,40,Милки Вей,860.0,Математический и ИТ,СоцГум,есть брат,У окна (пардон: у иллюминатора),15,10.0,40.0
10,20,158,35,4,2001,1000,85,72,0,0,...,600,КитКат,800000.0,Педагогический,Естественный (биология-химия-физика-технари),есть и брат и сестра,У прохода,10,9.0,15.0
11,19,183,44,2,2002,40,5,5,0,6,...,300,КитКат,880000.0,Математический и ИТ,Математический и ИТ,нет ни брата ни сестры,У окна (пардон: у иллюминатора),9,10.0,15.0
12,21,169,39,4,2001,150,68,27,0,0,...,240,M&Ms,800.0,Педагогический,Экономический,есть сестра,В середине,9,11.0,25.0

In [ ]:
df['Age']

0      20
1      22
2      21
3      19
4      23
       ..
181    23
182    19
183    18
184    19
185    18
Name: Age, Length: 186, dtype: int64

In [ ]:
df['Age'].describe()

count    186.000000
mean      20.688172
std        3.468713
min       17.000000
25%       19.000000
50%       20.000000
75%       21.000000
max       55.000000
Name: Age, dtype: float64

In [ ]:
df['Growth'].describe()

count    186.000000
mean     170.661290
std        9.055881
min      153.000000
25%      164.000000
50%      169.000000
75%      178.000000
max      197.000000
Name: Growth, dtype: float64

In [ ]:
df['Sex'].describe()

count         186
unique          2
top       женский
freq          120
Name: Sex, dtype: object

In [ ]:
df['Sex'].value_counts()

Sex
женский    120
мужской     66
Name: count, dtype: int64

In [ ]:
df['Chocolate'].value_counts()

Chocolate
КитКат                               35
Сникерс                              34
Твикс                                34
Баунти                               30
Милки Вей                            17
Натс                                 13
Марс                                 11
M&Ms                                  8
Скиттлс (хотя это и не шоколадка)     4
Name: count, dtype: int64

In [ ]:
df.describe()

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Height of 5000 mm,Width of 5000 mm,Putin age,Hair length,Floor number,Social network duration min,City population,MIddle and index finger,Middle and ring finger,Middle and little finger
count,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,186.000000,...,186.000000,186.000000,186.000000,186.000000,186.000000,1.860000e+02,1.860000e+02,186.000000,186.000000,186.000000
mean,20.688172,170.661290,39.715054,3.500000,1991.107527,374.032258,81.634409,58.177419,13.182796,32.801075,...,75.720430,177.688172,690.236559,34.365054,6.322581,5.417500e+08,7.946669e+05,9.741935,9.705376,28.798925
std,3.468713,9.055881,2.814920,3.147285,132.099550,2199.541507,14.325019,29.575478,26.414552,38.992282,...,107.747088,240.978320,7360.321689,25.672211,4.338791,7.332267e+09,6.093052e+05,4.385241,6.894963,19.710011
min,17.000000,153.000000,34.000000,0.000000,200.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,42.000000,0.200000,1.000000,0.000000e+00,1.000000e+00,0.000000,0.000000,0.000000
25%,19.000000,164.000000,38.000000,2.000000,2000.000000,74.500000,76.000000,50.000000,0.000000,0.000000,...,50.000000,100.000000,67.000000,12.000000,3.000000,1.200000e+02,7.000000e+05,7.000000,6.000000,20.000000
50%,20.000000,169.000000,39.000000,3.000000,2001.500000,130.000000,85.000000,70.000000,0.000000,0.000000,...,60.000000,140.000000,69.000000,30.000000,5.000000,2.000000e+02,8.000000e+05,10.000000,10.000000,28.500000
75%,21.000000,178.000000,42.000000,4.000000,2003.000000,236.000000,91.000000,76.750000,0.000000,75.000000,...,70.000000,167.250000,70.000000,50.000000,8.000000,3.600000e+02,8.845000e+05,12.000000,12.000000,35.000000
max,55.000000,197.000000,48.000000,37.000000,2004.000000,30000.000000,100.000000,100.000000,97.000000,98.000000,...,950.000000,1800.000000,100000.000000,150.000000,20.000000,1.000000e+11,8.000000e+06,30.000000,80.000000,250.000000

In [ ]:
df['Growth'].mean()

np.float64(170.66129032258064)

In [ ]:
df['Growth'].median()

169.0

In [ ]:
df['Growth'].min, df['Growth'].max, df['Growth'].std()

(<bound method Series.min of 0      170
 1      191
 2      172
 3      168
 4      159
       ...
 181    168
 182    169
 183    161
 184    169
 185    164
 Name: Growth, Length: 186, dtype: int64>,
 <bound method Series.max of 0      170
 1      191
 2      172
 3      168
 4      159
       ...
 181    168
 182    169
 183    161
 184    169
 185    164
 Name: Growth, Length: 186, dtype: int64>,
 9.055880959226974)

In [ ]:
df['Sex']
# взять из таблицы df то что относится к признаку пол

0      женский
1      мужской
2      мужской
3      женский
4      женский
        ...
181    женский
182    женский
183    женский
184    женский
185    женский
Name: Sex, Length: 186, dtype: object

In [ ]:
df_cut = df[['Growth', 'Weight', 'Sex', 'Age']]

In [ ]:
df_cut.head(11)

    Growth  Weight      Sex  Age
0      170    64.0  женский   20
1      191    73.0  мужской   22
2      172    60.0  мужской   21
3      168    59.0  женский   19
4      159    57.0  женский   23
5      177    50.0  мужской   18
6      180    55.0  мужской   18
7      180   120.0  мужской   19
8      185    69.0  мужской   20
9      168    58.0  женский   22
10     158    47.0  женский   20

In [ ]:
df['Weight'].mean()

np.float64(64.03184713375796)

In [ ]:
df['Weight'].median()

60.0

In [ ]:
df['Weight'].describe()

count    157.000000
mean      64.031847
std       16.502300
min        3.000000
25%       53.000000
50%       60.000000
75%       71.000000
max      120.000000
Name: Weight, dtype: float64

In [ ]:
df['Rock paper scissors'].value_counts()

Rock paper scissors
Ножницы    88
Камень     60
Бумага     38
Name: count, dtype: int64

In [ ]:
female=df[df['Sex']=='женский']

In [ ]:
female.head()

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
0,20,170,40,2,2002,100,85,86,0,84,...,45,Сникерс,800000.0,Экономический,Математический и ИТ,нет ни брата ни сестры,У окна (пардон: у иллюминатора),20,10.0,40.0
3,19,168,38,2,2003,604,72,0,0,0,...,200,Баунти,900000.0,СоцГум,Юридический,есть сестра,У окна (пардон: у иллюминатора),12,13.5,35.0
4,23,159,36,1,1998,144,0,0,0,0,...,400,Баунти,860000.0,Педагогический,Педагогический,есть сестра,У окна (пардон: у иллюминатора),10,11.0,22.0
9,22,168,38,6,2000,297,71,5,0,0,...,40,Милки Вей,860.0,Математический и ИТ,СоцГум,есть брат,У окна (пардон: у иллюминатора),15,10.0,40.0
10,20,158,35,4,2001,1000,85,72,0,0,...,600,КитКат,800000.0,Педагогический,Естественный (биология-химия-физика-технари),есть и брат и сестра,У прохода,10,9.0,15.0

In [ ]:
male=df[df['Sex']=='мужской']
male.head()

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
1,22,191,43,7,2000,307,69,74,64,72,...,180,КитКат,800000.0,Математический и ИТ,Математический и ИТ,есть и брат и сестра,В середине,5,5.0,20.0
2,21,172,41,4,2000,186,78,62,0,0,...,90,КитКат,770000.0,Педагогический,Другое,есть брат,У окна (пардон: у иллюминатора),13,10.0,26.0
5,18,177,40,2,2003,100,70,68,0,75,...,250,Сникерс,1200000.0,СоцГум,Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),12,7.0,30.0
6,18,180,42,0,2004,0,66,4,0,0,...,30,Сникерс,700000.0,Педагогический,Юридический,есть брат,У окна (пардон: у иллюминатора),5,30.0,35.0
7,19,180,48,1,2003,5,72,0,0,0,...,240,Баунти,880000.0,Естественный (биология-химия-физика-технари),Юридический,есть брат,У окна (пардон: у иллюминатора),7,5.0,25.0

In [ ]:
female['Growth'].mean(), male['Growth'].mean()

(np.float64(165.725), np.float64(179.63636363636363))

In [ ]:
female['Age'].mean(), male['Age'].mean()

(np.float64(21.033333333333335), np.float64(20.060606060606062))

In [ ]:
female['Age'].median(), male['Age'].median()

(20.0, 20.0)

In [ ]:
male['Coin'].value_counts()

Coin
Орел     54
Решка    12
Name: count, dtype: int64

In [ ]:
female['Coin'].value_counts()

Coin
Орел     64
Решка    56
Name: count, dtype: int64

In [ ]:
df1 = df[df['Growth']<165]
df3 = df[df['Growth']>175]
df2 = df[(165<=df['Growth']) & (df['Growth']<=175)]

In [ ]:
df1['Growth'].mean(), df2['Growth'].mean(), df3['Growth'].mean()

(np.float64(160.66666666666666),
 np.float64(169.16),
 np.float64(182.10526315789474))

In [ ]:
df[df['Age']+df['Year of birth']==2022].shape

(102, 48)

In [ ]:
df[df['Growth']<df['Growth'].mean()].shape

(110, 48)

In [ ]:
df[df['Age']==df['Age'].max()]

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
81,55,160,37,7,1960,2000,0,0,0,0,...,300,Милки Вей,800000.0,СоцГум,Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),10,10.0,10.0

In [ ]:
df[df['Age']==df['Age'].min()]

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
115,17,175,41,0,2004,152,96,80,0,83,...,1000,КитКат,1.0,СоцГум,Математический и ИТ,нет ни брата ни сестры,У окна (пардон: у иллюминатора),3,2.0,5.0
126,17,168,39,0,2004,110,91,72,0,83,...,1000,Марс,800000.0,Экономический,Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),5,7.0,15.0

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          186 non-null    int64
 1   Growth                       186 non-null    int64
 2   Shoe size                    186 non-null    int64
 3   Course number                186 non-null    int64
 4   Year of birth                186 non-null    int64
 5   Friend number                186 non-null    int64
 6   Russian rating               186 non-null    int64
 7   Maths rating                 186 non-null    int64
 8   Physics rating               186 non-null    int64
 9   Computer science rating      186 non-null    int64
 10  Chemistry rating             186 non-null    int64
 11  Literature rating            186 non-null    int64
 12  History rating               186 non-null    int64
 13  Geography rating             186 non-null    int64
 14  Biology rating               186 non-null    int64
 15  Foreign language rating      186 non-null    int64
 16  Social science rating        186 non-null    int64
 17  Distance to home km          186 non-null    int64
 18  Minutes to first class       186 non-null    int64
 19  Children number              150 non-null    float64
 20  Removed teeth                148 non-null    float64
 21  Weight                       157 non-null    float64
 22  Glasses                      184 non-null    object
 23  Sex                          186 non-null    object
 24  Problems in last semester    186 non-null    object
 25  Coin                         186 non-null    object
 26  Rock paper scissors          186 non-null    object
 27  Animal                       186 non-null    object
 28  Month of birthday            186 non-null    int64
 29  Your rating in university    186 non-null    object
 30  Fastfood                     186 non-null    object
 31  Height of 5000 mm            186 non-null    int64
 32  Width of 5000 mm             186 non-null    int64
 33  Putin age                    186 non-null    int64
 34  Army                         186 non-null    object
 35  Hostel                       186 non-null    object
 36  Hair length                  186 non-null    float64
 37  Floor number                 186 non-null    int64
 38  Social network duration min  186 non-null    int64
 39  Chocolate                    186 non-null    object
 40  City population              186 non-null    float64
 41  Strange people               186 non-null    object
 42  Your insitute                186 non-null    object
 43  Brother-sister               186 non-null    object
 44  Plane seat                   186 non-null    object
 45  MIddle and index finger      186 non-null    int64
 46  Middle and ring finger       186 non-null    float64
 47  Middle and little finger     186 non-null    float64
dtypes: float64(7), int64(26), object(15)
memory usage: 69.9+ KB

In [ ]:
df['Hostel'].value_counts()

Hostel
нет    173
да      13
Name: count, dtype: int64

In [ ]:
df[df['Weight']==120]

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
7,19,180,48,1,2003,5,72,0,0,0,...,240,Баунти,880000.0,Естественный (биология-химия-физика-технари),Юридический,есть брат,У окна (пардон: у иллюминатора),7,5.0,25.0

In [ ]:
df['Army'].value_counts()

Army
не призовут (по разным причинам)    149
могут призвать                       37
Name: count, dtype: int64

In [ ]:
army_persons=df[df['Army']=='могут призвать']
free_persons=df[df['Army']=='не призовут (по разным причинам)']

In [ ]:
army_persons.head()

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
2,21,172,41,4,2000,186,78,62,0,0,...,90,КитКат,770000.0,Педагогический,Другое,есть брат,У окна (пардон: у иллюминатора),13,10.0,26.0
5,18,177,40,2,2003,100,70,68,0,75,...,250,Сникерс,1200000.0,СоцГум,Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),12,7.0,30.0
7,19,180,48,1,2003,5,72,0,0,0,...,240,Баунти,880000.0,Естественный (биология-химия-физика-технари),Юридический,есть брат,У окна (пардон: у иллюминатора),7,5.0,25.0
11,19,183,44,2,2002,40,5,5,0,6,...,300,КитКат,880000.0,Математический и ИТ,Математический и ИТ,нет ни брата ни сестры,У окна (пардон: у иллюминатора),9,10.0,15.0
14,21,183,42,4,2000,89,83,70,69,73,...,2,Сникерс,1200000.0,Математический и ИТ,Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),11,6.0,30.0

In [ ]:
free_persons.head()

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
0,20,170,40,2,2002,100,85,86,0,84,...,45,Сникерс,800000.0,Экономический,Математический и ИТ,нет ни брата ни сестры,У окна (пардон: у иллюминатора),20,10.0,40.0
1,22,191,43,7,2000,307,69,74,64,72,...,180,КитКат,800000.0,Математический и ИТ,Математический и ИТ,есть и брат и сестра,В середине,5,5.0,20.0
3,19,168,38,2,2003,604,72,0,0,0,...,200,Баунти,900000.0,СоцГум,Юридический,есть сестра,У окна (пардон: у иллюминатора),12,13.5,35.0
4,23,159,36,1,1998,144,0,0,0,0,...,400,Баунти,860000.0,Педагогический,Педагогический,есть сестра,У окна (пардон: у иллюминатора),10,11.0,22.0
6,18,180,42,0,2004,0,66,4,0,0,...,30,Сникерс,700000.0,Педагогический,Юридический,есть брат,У окна (пардон: у иллюминатора),5,30.0,35.0

In [ ]:
army_persons['Hair length'].value_counts()

Sex
мужской    36
женский     1
Name: count, dtype: int64

In [ ]:
df[(free_persons['Sex']=='мужской') & (free_person['Hair length'])]

NameError: name 'free_person' is not defined

In [ ]:
print(army_persons['Hair length'].mean())

11.045945945945945

In [ ]:
df[(df['Friend number']==0) & (df['Sex']=='мужской')]

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
6,18,180,42,0,2004,0,66,4,0,0,...,30,Сникерс,700000.0,Педагогический,Юридический,есть брат,У окна (пардон: у иллюминатора),5,30.0,35.0

In [ ]:
df['Animal'].value_counts()

Animal
Кошек                     115
Собак                      60
Ненавижу этих животных     11
Name: count, dtype: int64

In [ ]:
dor_lovers = df[df['Animal']=='Собак']

In [ ]:
dor_lovers['Floor number'].value_counts()

Floor number
4     12
1      7
5      6
2      5
6      5
7      4
9      3
3      3
11     3
14     2
10     2
12     2
8      2
16     1
17     1
15     1
13     1
Name: count, dtype: int64

In [ ]:
(7/60)*100

11.666666666666666

In [ ]:
df['Brother-sister'].value_counts()

Brother-sister
есть брат                 62
есть сестра               55
нет ни брата ни сестры    39
есть и брат и сестра      30
Name: count, dtype: int64

In [ ]:
single_child = df[df['Brother-sister'] != 'нет ни брата ни сестры']

In [ ]:
not_single_child = df[df['Brother-sister'] == 'нет ни брата ни сестры']

In [ ]:
single_child['Social network duration min'].median()

180.0

In [ ]:
not_single_child['Social network duration min'].median()

240.0

In [ ]:
not_single_child['Social network duration min'].median()-single_child['Social network duration min'].median()

60.0

In [ ]:
df['Fastfood'].value_counts()

Fastfood
KFC                                                82
Бургер кинг                                        56
Макдональдс (или как он там сейчас называется?)    48
Name: count, dtype: int64

In [ ]:
KFC_persons = df[df['Fastfood']=='KFC']

In [ ]:
Burger_persons = df[df['Fastfood']=='Бургер кинг']

In [ ]:
Mac_persons = df[df['Fastfood']=='Макдональдс (или как он там сейчас называется?)']

In [ ]:
KFC_persons['Weight'].mean()

np.float64(66.85915492957747)

In [ ]:
Burger_persons['Weight'].mean()

np.float64(64.21739130434783)

In [ ]:
Mac_persons['Weight'].mean()

np.float64(58.8)

In [ ]:
KFC_persons['Weight'].mean()-Mac_persons['Weight'].mean()

np.float64(8.059154929577474)

In [ ]:
df_cut=df[['Age', 'Growth', 'Weight']]
df_cut.head()

   Age  Growth  Weight
0   20     170    64.0
1   22     191    73.0
2   21     172    60.0
3   19     168    59.0
4   23     159    57.0

In [ ]:
df_cut.sort_values(by='Age', ascending=False)

     Age  Growth  Weight
81    55     160     3.0
63    35     180    78.0
99    31     165    53.0
173   29     176    70.0
82    27     168    58.0
..   ...     ...     ...
127   18     165    46.0
185   18     164    54.0
175   18     176    58.0
115   17     175    72.0
126   17     168    71.0

[186 rows x 3 columns]

In [ ]:
df_cut.sort_values(['Age', 'Growth'], ascending=[False, False])

     Age  Growth  Weight
81    55     160     3.0
63    35     180    78.0
99    31     165    53.0
173   29     176    70.0
82    27     168    58.0
..   ...     ...     ...
47    18     159     NaN
94    18     158    53.0
118   18     157    59.0
115   17     175    72.0
126   17     168    71.0

[186 rows x 3 columns]

In [ ]:
df_cut.sort_values(['Growth', 'Age'], ascending=[False, False])

     Age  Growth  Weight
103   19     197   100.0
27    19     193    61.0
1     22     191    73.0
87    23     188    83.0
33    22     188    95.0
..   ...     ...     ...
118   18     157    59.0
53    19     156    48.0
177   23     155    50.0
34    19     155     NaN
152   19     153    46.0

[186 rows x 3 columns]

     Age  Growth  Weight
103   19     197   100.0
27    19     193    61.0
1     22     191    73.0
87    23     188    83.0
33    22     188    95.0
..   ...     ...     ...
118   18     157    59.0
53    19     156    48.0
177   23     155    50.0
34    19     155     NaN
152   19     153    46.0

[186 rows x 3 columns]

In [ ]:
df_sorted=df_cut.sort_values('Growth', ascending=False)
df_sorted.iloc[2,]

Age        22.0
Growth    191.0
Weight     73.0
Name: 1, dtype: float64

In [ ]:
df_sorted.iloc[2,0]

np.int64(22)

In [ ]:
df_cut['Mass index']=100*100*df_cut['Weight']/(df_cut['Growth']*df_cut['Growth'])

/tmp/ipykernel_7980/2490834078.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cut['Mass index']=100*100*df_cut['Weight']/(df_cut['Growth']*df_cut['Growth'])

In [ ]:
df_cut.head()

   Age  Growth  Weight  Mass index
0   20     170    64.0   22.145329
1   22     191    73.0   20.010416
2   21     172    60.0   20.281233
3   19     168    59.0   20.904195
4   23     159    57.0   22.546576

In [ ]:
df_cut.sort_values(by='Mass index', ascending=False)

     Age  Growth  Weight  Mass index
149   22     173   115.0   38.424271
7     19     180   120.0   37.037037
28    20     163    90.0   33.874064
124   21     163    88.0   33.121307
69    20     181   105.0   32.050304
..   ...     ...     ...         ...
158   21     168     NaN         NaN
161   24     163     NaN         NaN
167   21     168     NaN         NaN
170   22     168     NaN         NaN
178   21     170     NaN         NaN

[186 rows x 4 columns]

In [ ]:
df_cut.corr()

                 Age    Growth    Weight  Mass index
Age         1.000000 -0.101982 -0.185722   -0.200305
Growth     -0.101982  1.000000  0.544528    0.146201
Weight     -0.185722  0.544528  1.000000    0.904678
Mass index -0.200305  0.146201  0.904678    1.000000

In [ ]:
df.groupby('Sex')['Growth'].mean()

Sex
женский    165.725000
мужской    179.636364
Name: Growth, dtype: float64

In [ ]:
df.groupby('Sex')[['Growth', 'Weight']].mean()

             Growth     Weight
Sex
женский  165.725000  59.105263
мужской  179.636364  71.580645

In [ ]:
df.groupby('Sex')[['Russian rating', 'Maths rating']].mean()

         Russian rating  Maths rating
Sex
женский       83.633333     55.516667
мужской       78.000000     63.015152

In [ ]:
df.groupby(['Sex','Chocolate'])[['Russian rating', 'Maths rating']].mean()

                                           Russian rating  Maths rating
Sex     Chocolate
женский M&Ms                                    79.400000     51.600000
        Баунти                                  81.181818     56.318182
        КитКат                                  85.782609     61.782609
        Марс                                    91.166667     36.666667
        Милки Вей                               79.583333     45.250000
        Натс                                    84.636364     53.818182
        Скиттлс (хотя это и не шоколадка)       86.000000     67.000000
        Сникерс                                 80.375000     61.562500
        Твикс                                   86.478261     55.217391
мужской M&Ms                                    83.666667     76.666667
        Баунти                                  78.375000     68.000000
        КитКат                                  74.416667     51.083333
        Марс                                    85.600000     55.400000
        Милки Вей                               72.800000     61.800000
        Натс                                    70.500000     72.000000
        Скиттлс (хотя это и не шоколадка)       84.000000     77.000000
        Сникерс                                 77.666667     59.055556
        Твикс                                   79.818182     75.000000

In [ ]:
df.groupby('Chocolate')[['Russian rating', 'Maths rating']].mean()

                                   Russian rating  Maths rating
Chocolate
M&Ms                                    81.000000     61.000000
Баунти                                  80.433333     59.433333
КитКат                                  81.885714     58.114286
Марс                                    88.636364     45.181818
Милки Вей                               77.588235     50.117647
Натс                                    82.461538     56.615385
Скиттлс (хотя это и не шоколадка)       85.000000     72.000000
Сникерс                                 78.941176     60.235294
Твикс                                   84.323529     61.617647

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          186 non-null    int64
 1   Growth                       186 non-null    int64
 2   Shoe size                    186 non-null    int64
 3   Course number                186 non-null    int64
 4   Year of birth                186 non-null    int64
 5   Friend number                186 non-null    int64
 6   Russian rating               186 non-null    int64
 7   Maths rating                 186 non-null    int64
 8   Physics rating               186 non-null    int64
 9   Computer science rating      186 non-null    int64
 10  Chemistry rating             186 non-null    int64
 11  Literature rating            186 non-null    int64
 12  History rating               186 non-null    int64
 13  Geography rating             186 non-null    int64
 14  Biology rating               186 non-null    int64
 15  Foreign language rating      186 non-null    int64
 16  Social science rating        186 non-null    int64
 17  Distance to home km          186 non-null    int64
 18  Minutes to first class       186 non-null    int64
 19  Children number              150 non-null    float64
 20  Removed teeth                148 non-null    float64
 21  Weight                       157 non-null    float64
 22  Glasses                      184 non-null    object
 23  Sex                          186 non-null    object
 24  Problems in last semester    186 non-null    object
 25  Coin                         186 non-null    object
 26  Rock paper scissors          186 non-null    object
 27  Animal                       186 non-null    object
 28  Month of birthday            186 non-null    int64
 29  Your rating in university    186 non-null    object
 30  Fastfood                     186 non-null    object
 31  Height of 5000 mm            186 non-null    int64
 32  Width of 5000 mm             186 non-null    int64
 33  Putin age                    186 non-null    int64
 34  Army                         186 non-null    object
 35  Hostel                       186 non-null    object
 36  Hair length                  186 non-null    float64
 37  Floor number                 186 non-null    int64
 38  Social network duration min  186 non-null    int64
 39  Chocolate                    186 non-null    object
 40  City population              186 non-null    float64
 41  Strange people               186 non-null    object
 42  Your insitute                186 non-null    object
 43  Brother-sister               186 non-null    object
 44  Plane seat                   186 non-null    object
 45  MIddle and index finger      186 non-null    int64
 46  Middle and ring finger       186 non-null    float64
 47  Middle and little finger     186 non-null    float64
dtypes: float64(7), int64(26), object(15)
memory usage: 69.9+ KB

In [ ]:
df_cut2=df[['Year of birth', 'Weight', 'Growth', 'Hair length', 'Shoe size']]
df_cut2

     Year of birth  Weight  Growth  Hair length  Shoe size
0             2002    64.0     170         50.0         40
1             2000    73.0     191          7.0         43
2             2000    60.0     172          4.0         41
3             2003    59.0     168         20.0         38
4             1998    57.0     159         55.0         36
..             ...     ...     ...          ...        ...
181           1999    59.0     168         30.0         39
182           2003    43.0     169         45.0         38
183           2003    51.0     161         40.0         37
184           2003    62.0     169        150.0         41
185           2003    54.0     164         60.0         39

[186 rows x 5 columns]

In [ ]:
df_cut2.sort_values(['Shoe size'], ascending=False)

     Year of birth  Weight  Growth  Hair length  Shoe size
7             2003   120.0     180         20.0         48
27            2003    61.0     193          3.0         48
8             2002    69.0     185         25.0         46
103           2002   100.0     197         23.0         46
55            1999    92.0     180          0.2         45
..             ...     ...     ...          ...        ...
10            2001    47.0     158         50.0         35
116           1999    48.0     158         55.0         35
118           2003    59.0     157         30.0         35
138           2001     NaN     158        100.0         35
96            2003    56.0     163         50.0         34

[186 rows x 5 columns]

In [ ]:
df_cut2.sort_values(['Shoe size', 'Growth'], ascending=[True, True]).head(10)

     Year of birth  Weight  Growth  Hair length  Shoe size
96            2003    56.0     163         50.0         34
118           2003    59.0     157         30.0         35
10            2001    47.0     158         50.0         35
37            1997    60.0     158         60.0         35
116           1999    48.0     158         55.0         35
138           2001     NaN     158        100.0         35
47            2004     NaN     159         25.0         35
52            2002    53.0     163         55.0         35
177           1999    50.0     155         70.0         36
117           2002     NaN     157         40.0         36

In [ ]:
df_cut2.sort_values(['Shoe size', 'Growth'], ascending=[True, False]).head(10)

     Year of birth  Weight  Growth  Hair length  Shoe size
96            2003    56.0     163         50.0         34
52            2002    53.0     163         55.0         35
47            2004     NaN     159         25.0         35
10            2001    47.0     158         50.0         35
37            1997    60.0     158         60.0         35
116           1999    48.0     158         55.0         35
138           2001     NaN     158        100.0         35
118           2003    59.0     157         30.0         35
180           2000    50.0     167         45.0         36
127           2003    46.0     165         60.0         36

In [ ]:
df_cut2.sort_values(['Shoe size', 'Growth'], ascending=[False, True]).head(10)

     Year of birth  Weight  Growth  Hair length  Shoe size
7             2003   120.0     180         20.0         48
27            2003    61.0     193          3.0         48
8             2002    69.0     185         25.0         46
103           2002   100.0     197         23.0         46
55            1999    92.0     180          0.2         45
76            2002     NaN     184         20.0         45
145           1999    92.0     184         45.0         45
16            2003    64.0     185          4.0         45
20            2001    93.0     186         20.0         45
24            2002    65.0     177         12.0         44

In [ ]:
df_cut2['Full length']=df_cut2['Hair length']+df_cut2['Growth']