<a href="https://colab.research.google.com/github/Kristina-aut/For-example-Task-_dataset_studets/blob/main/Task_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import numpy as np

In [ ]:
df=pd.read_csv('/content/students.csv', delimiter=',')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          186 non-null    int64
 1   Growth                       186 non-null    int64
 2   Shoe size                    186 non-null    int64
 3   Course number                186 non-null    int64
 4   Year of birth                186 non-null    int64
 5   Friend number                186 non-null    int64
 6   Russian rating               186 non-null    int64
 7   Maths rating                 186 non-null    int64
 8   Physics rating               186 non-null    int64
 9   Computer science rating      186 non-null    int64
 10  Chemistry rating             186 non-null    int64
 11  Literature rating            186 non-null    int64
 12  History rating               186 non-null    int64
 13  Geography rating             186 non-null    int64
 14  Biology rating               186 non-null    int64
 15  Foreign language rating      186 non-null    int64
 16  Social science rating        186 non-null    int64
 17  Distance to home km          186 non-null    int64
 18  Minutes to first class       186 non-null    int64
 19  Children number              150 non-null    float64
 20  Removed teeth                148 non-null    float64
 21  Weight                       157 non-null    float64
 22  Glasses                      184 non-null    object
 23  Sex                          186 non-null    object
 24  Problems in last semester    186 non-null    object
 25  Coin                         186 non-null    object
 26  Rock paper scissors          186 non-null    object
 27  Animal                       186 non-null    object
 28  Month of birthday            186 non-null    int64
 29  Your rating in university    186 non-null    object
 30  Fastfood                     186 non-null    object
 31  Height of 5000 mm            186 non-null    int64
 32  Width of 5000 mm             186 non-null    int64
 33  Putin age                    186 non-null    int64
 34  Army                         186 non-null    object
 35  Hostel                       186 non-null    object
 36  Hair length                  186 non-null    float64
 37  Floor number                 186 non-null    int64
 38  Social network duration min  186 non-null    int64
 39  Chocolate                    186 non-null    object
 40  City population              186 non-null    float64
 41  Strange people               186 non-null    object
 42  Your insitute                186 non-null    object
 43  Brother-sister               186 non-null    object
 44  Plane seat                   186 non-null    object
 45  MIddle and index finger      186 non-null    int64
 46  Middle and ring finger       186 non-null    float64
 47  Middle and little finger     186 non-null    float64
dtypes: float64(7), int64(26), object(15)
memory usage: 69.9+ KB

In [ ]:
df['Hostel'].value_counts()

Hostel
нет    173
да      13
Name: count, dtype: int64

In [ ]:
df[df['Weight']==120]

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
7,19,180,48,1,2003,5,72,0,0,0,...,240,Баунти,880000.0,Естественный (биология-химия-физика-технари),Юридический,есть брат,У окна (пардон: у иллюминатора),7,5.0,25.0

In [ ]:
df['Army'].value_counts()

Army
не призовут (по разным причинам)    149
могут призвать                       37
Name: count, dtype: int64

In [ ]:
army_persons=df[df['Army']=='могут призвать']
free_persons=df[df['Army']=='не призовут (по разным причинам)']

In [ ]:
army_persons.head()

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
2,21,172,41,4,2000,186,78,62,0,0,...,90,КитКат,770000.0,Педагогический,Другое,есть брат,У окна (пардон: у иллюминатора),13,10.0,26.0
5,18,177,40,2,2003,100,70,68,0,75,...,250,Сникерс,1200000.0,СоцГум,Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),12,7.0,30.0
7,19,180,48,1,2003,5,72,0,0,0,...,240,Баунти,880000.0,Естественный (биология-химия-физика-технари),Юридический,есть брат,У окна (пардон: у иллюминатора),7,5.0,25.0
11,19,183,44,2,2002,40,5,5,0,6,...,300,КитКат,880000.0,Математический и ИТ,Математический и ИТ,нет ни брата ни сестры,У окна (пардон: у иллюминатора),9,10.0,15.0
14,21,183,42,4,2000,89,83,70,69,73,...,2,Сникерс,1200000.0,Математический и ИТ,Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),11,6.0,30.0

In [ ]:
free_persons.head()

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
0,20,170,40,2,2002,100,85,86,0,84,...,45,Сникерс,800000.0,Экономический,Математический и ИТ,нет ни брата ни сестры,У окна (пардон: у иллюминатора),20,10.0,40.0
1,22,191,43,7,2000,307,69,74,64,72,...,180,КитКат,800000.0,Математический и ИТ,Математический и ИТ,есть и брат и сестра,В середине,5,5.0,20.0
3,19,168,38,2,2003,604,72,0,0,0,...,200,Баунти,900000.0,СоцГум,Юридический,есть сестра,У окна (пардон: у иллюминатора),12,13.5,35.0
4,23,159,36,1,1998,144,0,0,0,0,...,400,Баунти,860000.0,Педагогический,Педагогический,есть сестра,У окна (пардон: у иллюминатора),10,11.0,22.0
6,18,180,42,0,2004,0,66,4,0,0,...,30,Сникерс,700000.0,Педагогический,Юридический,есть брат,У окна (пардон: у иллюминатора),5,30.0,35.0

In [ ]:
army_persons['Hair length'].value_counts()

Hair length
3.0     5
5.0     4
10.0    3
2.0     3
20.0    3
4.0     2
25.0    2
12.0    2
15.0    2
8.0     2
7.0     2
30.0    1
1.0     1
0.2     1
23.0    1
35.0    1
1.5     1
45.0    1
Name: count, dtype: int64

In [ ]:
df[(free_persons['Sex']=='мужской') & (free_person['Hair length'])]

NameError: name 'free_person' is not defined

In [ ]:
print(army_persons['Hair length'].mean())

11.045945945945945

In [ ]:
df[(df['Friend number']==0) & (df['Sex']=='мужской')]

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
6,18,180,42,0,2004,0,66,4,0,0,...,30,Сникерс,700000.0,Педагогический,Юридический,есть брат,У окна (пардон: у иллюминатора),5,30.0,35.0

In [ ]:
df['Animal'].value_counts()

Animal
Кошек                     115
Собак                      60
Ненавижу этих животных     11
Name: count, dtype: int64

In [ ]:
dor_lovers = df[df['Animal']=='Собак']

In [ ]:
dor_lovers['Floor number'].value_counts()

Floor number
4     12
1      7
5      6
2      5
6      5
7      4
9      3
3      3
11     3
14     2
10     2
12     2
8      2
16     1
17     1
15     1
13     1
Name: count, dtype: int64

In [ ]:
df['Brother-sister'].value_counts()

Brother-sister
есть брат                 62
есть сестра               55
нет ни брата ни сестры    39
есть и брат и сестра      30
Name: count, dtype: int64

In [ ]:
single_child = df[df['Brother-sister'] != 'нет ни брата ни сестры']

In [ ]:
not_single_child = df[df['Brother-sister'] == 'нет ни брата ни сестры']

In [ ]:
single_child['Social network duration min'].median()

180.0

In [ ]:
not_single_child['Social network duration min'].median()

240.0

In [ ]:
not_single_child['Social network duration min'].median()-single_child['Social network duration min'].median()

60.0

In [ ]:
df['Fastfood'].value_counts()

Fastfood
KFC                                                82
Бургер кинг                                        56
Макдональдс (или как он там сейчас называется?)    48
Name: count, dtype: int64

In [ ]:
KFC_persons = df[df['Fastfood']=='KFC']

In [ ]:
Burger_persons = df[df['Fastfood']=='Бургер кинг']

In [ ]:
Mac_persons = df[df['Fastfood']=='Макдональдс (или как он там сейчас называется?)']

In [ ]:
KFC_persons['Weight'].mean()

np.float64(66.85915492957747)

In [ ]:
Burger_persons['Weight'].mean()

np.float64(64.21739130434783)

In [ ]:
Mac_persons['Weight'].mean()

np.float64(58.8)

In [ ]:
KFC_persons['Weight'].mean()-Mac_persons['Weight'].mean()

np.float64(8.059154929577474)

In [ ]:
df_cut=df[['Age', 'Growth', 'Weight']]
df_cut.head()

   Age  Growth  Weight
0   20     170    64.0
1   22     191    73.0
2   21     172    60.0
3   19     168    59.0
4   23     159    57.0

In [ ]:
df_cut.sort_values(by='Age', ascending=False)

     Age  Growth  Weight
81    55     160     3.0
63    35     180    78.0
99    31     165    53.0
173   29     176    70.0
82    27     168    58.0
..   ...     ...     ...
127   18     165    46.0
185   18     164    54.0
175   18     176    58.0
115   17     175    72.0
126   17     168    71.0

[186 rows x 3 columns]

In [ ]:
df_cut.sort_values(['Age', 'Growth'], ascending=[False, False])

     Age  Growth  Weight
81    55     160     3.0
63    35     180    78.0
99    31     165    53.0
173   29     176    70.0
82    27     168    58.0
..   ...     ...     ...
47    18     159     NaN
94    18     158    53.0
118   18     157    59.0
115   17     175    72.0
126   17     168    71.0

[186 rows x 3 columns]

In [ ]:
df_cut.sort_values(['Growth', 'Age'], ascending=[False, False])

     Age  Growth  Weight
103   19     197   100.0
27    19     193    61.0
1     22     191    73.0
87    23     188    83.0
33    22     188    95.0
..   ...     ...     ...
118   18     157    59.0
53    19     156    48.0
177   23     155    50.0
34    19     155     NaN
152   19     153    46.0

[186 rows x 3 columns]

In [ ]:
df_sorted=df_cut.sort_values('Growth', ascending=False)
df_sorted.iloc[2,]

Age        22.0
Growth    191.0
Weight     73.0
Name: 1, dtype: float64

In [ ]:
df_sorted.iloc[2,0]

np.int64(22)

In [ ]:
df_cut['Mass index']=100*100*df_cut['Weight']/(df_cut['Growth']*df_cut['Growth'])

/tmp/ipykernel_484/2490834078.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cut['Mass index']=100*100*df_cut['Weight']/(df_cut['Growth']*df_cut['Growth'])

In [ ]:
df_cut.head()

   Age  Growth  Weight
0   20     170    64.0
1   22     191    73.0
2   21     172    60.0
3   19     168    59.0
4   23     159    57.0

In [ ]:
df_cut.sort_values(by='Mass index', ascending=False)

     Age  Growth  Weight  Mass index
149   22     173   115.0   38.424271
7     19     180   120.0   37.037037
28    20     163    90.0   33.874064
124   21     163    88.0   33.121307
69    20     181   105.0   32.050304
..   ...     ...     ...         ...
158   21     168     NaN         NaN
161   24     163     NaN         NaN
167   21     168     NaN         NaN
170   22     168     NaN         NaN
178   21     170     NaN         NaN

[186 rows x 4 columns]

In [ ]:
df_cut.corr()

                 Age    Growth    Weight  Mass index
Age         1.000000 -0.101982 -0.185722   -0.200305
Growth     -0.101982  1.000000  0.544528    0.146201
Weight     -0.185722  0.544528  1.000000    0.904678
Mass index -0.200305  0.146201  0.904678    1.000000

In [ ]:
df.groupby('Sex')['Growth'].mean()

Sex
женский    165.725000
мужской    179.636364
Name: Growth, dtype: float64

In [ ]:
df.groupby('Sex')[['Growth', 'Weight']].mean()

             Growth     Weight
Sex
женский  165.725000  59.105263
мужской  179.636364  71.580645

In [ ]:
df.groupby('Sex')[['Russian rating', 'Maths rating']].mean()

         Russian rating  Maths rating
Sex
женский       83.633333     55.516667
мужской       78.000000     63.015152

In [ ]:
df.groupby(['Sex','Chocolate'])[['Russian rating', 'Maths rating']].mean()

                                           Russian rating  Maths rating
Sex     Chocolate
женский M&Ms                                    79.400000     51.600000
        Баунти                                  81.181818     56.318182
        КитКат                                  85.782609     61.782609
        Марс                                    91.166667     36.666667
        Милки Вей                               79.583333     45.250000
        Натс                                    84.636364     53.818182
        Скиттлс (хотя это и не шоколадка)       86.000000     67.000000
        Сникерс                                 80.375000     61.562500
        Твикс                                   86.478261     55.217391
мужской M&Ms                                    83.666667     76.666667
        Баунти                                  78.375000     68.000000
        КитКат                                  74.416667     51.083333
        Марс                                    85.600000     55.400000
        Милки Вей                               72.800000     61.800000
        Натс                                    70.500000     72.000000
        Скиттлс (хотя это и не шоколадка)       84.000000     77.000000
        Сникерс                                 77.666667     59.055556
        Твикс                                   79.818182     75.000000

In [ ]:
df.groupby('Chocolate')[['Russian rating', 'Maths rating']].mean()

                                   Russian rating  Maths rating
Chocolate
M&Ms                                    81.000000     61.000000
Баунти                                  80.433333     59.433333
КитКат                                  81.885714     58.114286
Марс                                    88.636364     45.181818
Милки Вей                               77.588235     50.117647
Натс                                    82.461538     56.615385
Скиттлс (хотя это и не шоколадка)       85.000000     72.000000
Сникерс                                 78.941176     60.235294
Твикс                                   84.323529     61.617647

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          186 non-null    int64
 1   Growth                       186 non-null    int64
 2   Shoe size                    186 non-null    int64
 3   Course number                186 non-null    int64
 4   Year of birth                186 non-null    int64
 5   Friend number                186 non-null    int64
 6   Russian rating               186 non-null    int64
 7   Maths rating                 186 non-null    int64
 8   Physics rating               186 non-null    int64
 9   Computer science rating      186 non-null    int64
 10  Chemistry rating             186 non-null    int64
 11  Literature rating            186 non-null    int64
 12  History rating               186 non-null    int64
 13  Geography rating             186 non-null    int64
 14  Biology rating               186 non-null    int64
 15  Foreign language rating      186 non-null    int64
 16  Social science rating        186 non-null    int64
 17  Distance to home km          186 non-null    int64
 18  Minutes to first class       186 non-null    int64
 19  Children number              150 non-null    float64
 20  Removed teeth                148 non-null    float64
 21  Weight                       157 non-null    float64
 22  Glasses                      184 non-null    object
 23  Sex                          186 non-null    object
 24  Problems in last semester    186 non-null    object
 25  Coin                         186 non-null    object
 26  Rock paper scissors          186 non-null    object
 27  Animal                       186 non-null    object
 28  Month of birthday            186 non-null    int64
 29  Your rating in university    186 non-null    object
 30  Fastfood                     186 non-null    object
 31  Height of 5000 mm            186 non-null    int64
 32  Width of 5000 mm             186 non-null    int64
 33  Putin age                    186 non-null    int64
 34  Army                         186 non-null    object
 35  Hostel                       186 non-null    object
 36  Hair length                  186 non-null    float64
 37  Floor number                 186 non-null    int64
 38  Social network duration min  186 non-null    int64
 39  Chocolate                    186 non-null    object
 40  City population              186 non-null    float64
 41  Strange people               186 non-null    object
 42  Your insitute                186 non-null    object
 43  Brother-sister               186 non-null    object
 44  Plane seat                   186 non-null    object
 45  MIddle and index finger      186 non-null    int64
 46  Middle and ring finger       186 non-null    float64
 47  Middle and little finger     186 non-null    float64
dtypes: float64(7), int64(26), object(15)
memory usage: 69.9+ KB

In [ ]:
df_cut2=df[['Year of birth', 'Weight', 'Growth', 'Hair length', 'Shoe size']]
df_cut2

     Year of birth  Weight  Growth  Hair length  Shoe size
0             2002    64.0     170         50.0         40
1             2000    73.0     191          7.0         43
2             2000    60.0     172          4.0         41
3             2003    59.0     168         20.0         38
4             1998    57.0     159         55.0         36
..             ...     ...     ...          ...        ...
181           1999    59.0     168         30.0         39
182           2003    43.0     169         45.0         38
183           2003    51.0     161         40.0         37
184           2003    62.0     169        150.0         41
185           2003    54.0     164         60.0         39

[186 rows x 5 columns]

In [ ]:
df_cut2.sort_values(['Shoe size'], ascending=False)

     Year of birth  Weight  Growth  Hair length  Shoe size
7             2003   120.0     180         20.0         48
27            2003    61.0     193          3.0         48
8             2002    69.0     185         25.0         46
103           2002   100.0     197         23.0         46
55            1999    92.0     180          0.2         45
..             ...     ...     ...          ...        ...
10            2001    47.0     158         50.0         35
116           1999    48.0     158         55.0         35
118           2003    59.0     157         30.0         35
138           2001     NaN     158        100.0         35
96            2003    56.0     163         50.0         34

[186 rows x 5 columns]

In [ ]:
df_cut2.sort_values(['Shoe size', 'Growth'], ascending=[True, True]).head(10)

     Year of birth  Weight  Growth  Hair length  Shoe size
96            2003    56.0     163         50.0         34
118           2003    59.0     157         30.0         35
10            2001    47.0     158         50.0         35
37            1997    60.0     158         60.0         35
116           1999    48.0     158         55.0         35
138           2001     NaN     158        100.0         35
47            2004     NaN     159         25.0         35
52            2002    53.0     163         55.0         35
177           1999    50.0     155         70.0         36
117           2002     NaN     157         40.0         36

In [ ]:
df_cut2.sort_values(['Shoe size', 'Growth'], ascending=[True, False]).head(10)

     Year of birth  Weight  Growth  Hair length  Shoe size
96            2003    56.0     163         50.0         34
52            2002    53.0     163         55.0         35
47            2004     NaN     159         25.0         35
10            2001    47.0     158         50.0         35
37            1997    60.0     158         60.0         35
116           1999    48.0     158         55.0         35
138           2001     NaN     158        100.0         35
118           2003    59.0     157         30.0         35
180           2000    50.0     167         45.0         36
127           2003    46.0     165         60.0         36

In [ ]:
df_cut2.sort_values(['Shoe size', 'Growth'], ascending=[False, True]).head(10)

     Year of birth  Weight  Growth  Hair length  Shoe size
7             2003   120.0     180         20.0         48
27            2003    61.0     193          3.0         48
8             2002    69.0     185         25.0         46
103           2002   100.0     197         23.0         46
55            1999    92.0     180          0.2         45
76            2002     NaN     184         20.0         45
145           1999    92.0     184         45.0         45
16            2003    64.0     185          4.0         45
20            2001    93.0     186         20.0         45
24            2002    65.0     177         12.0         44

In [ ]:
df_cut2['Full length']=df_cut2['Hair length']+df_cut2['Growth']

/tmp/ipykernel_484/3774786597.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_cut2['Full length']=df_cut2['Hair length']+df_cut2['Growth']

In [ ]:
df_cut2.sort_values(['Full length'], ascending=False)

     Year of birth  Weight  Growth  Hair length  Shoe size  Full length
184           2003    62.0     169        150.0         41        319.0
108           2001    65.0     164        100.0         37        264.0
80            2000    60.0     163        100.0         37        263.0
79            1998    62.0     170         90.0         39        260.0
68            2001     NaN     170         90.0         40        260.0
..             ...     ...     ...          ...        ...          ...
34            2003     NaN     155         20.0         37        175.0
134           1998    84.0     163         12.0         39        175.0
78            2003    64.0     170          5.0         40        175.0
106           2002    70.0     170          4.0         42        174.0
151           1997    71.0     167          3.0         41        170.0

[186 rows x 6 columns]

In [ ]:
df_cut2.corr()

,Year of birth,Weight,Growth,Hair length,Shoe size,Full length
Year of birth,1.000000,0.006042,-0.113357,0.095402,-0.108360,0.064713
Weight,0.006042,1.000000,0.544528,-0.319416,0.591149,-0.145316
Growth,-0.113357,0.544528,1.000000,-0.554408,0.863252,-0.235492
Hair length,0.095402,-0.319416,-0.554408,1.000000,-0.567568,0.939398
Shoe size,-0.108360,0.591149,0.863252,-0.567568,1.000000,-0.307190
Full length,0.064713,-0.145316,-0.235492,0.939398,-0.307190,1.000000

In [ ]:
df.groupby('Glasses')[['Russian rating', 'Maths rating']].mean()

                                     Russian rating  Maths rating
Glasses
да                                        83.388235     56.741176
нет                                       80.471910     59.955056
простите. не увидел(а) вопроса ))))       77.900000     54.700000

In [ ]:
df.groupby('Rock paper scissors')[['Russian rating', 'Maths rating']].mean()

                     Russian rating  Maths rating
Rock paper scissors
Бумага                    76.473684     52.894737
Камень                    81.450000     62.166667
Ножницы                   83.988636     57.738636