<a href="https://colab.research.google.com/github/Kristina-aut/For-example-Task-_dataset_studets/blob/main/%D0%9F%D1%80%D0%BE%D0%BF%D1%83%D1%81%D0%BA%D0%B8_%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D1%85.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv('/content/students.csv', delimiter=',')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 186 entries, 0 to 185
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          186 non-null    int64
 1   Growth                       186 non-null    int64
 2   Shoe size                    186 non-null    int64
 3   Course number                186 non-null    int64
 4   Year of birth                186 non-null    int64
 5   Friend number                186 non-null    int64
 6   Russian rating               186 non-null    int64
 7   Maths rating                 186 non-null    int64
 8   Physics rating               186 non-null    int64
 9   Computer science rating      186 non-null    int64
 10  Chemistry rating             186 non-null    int64
 11  Literature rating            186 non-null    int64
 12  History rating               186 non-null    int64
 13  Geography rating             186 non-null    int64
 14  Biology rating               186 non-null    int64
 15  Foreign language rating      186 non-null    int64
 16  Social science rating        186 non-null    int64
 17  Distance to home km          186 non-null    int64
 18  Minutes to first class       186 non-null    int64
 19  Children number              150 non-null    float64
 20  Removed teeth                148 non-null    float64
 21  Weight                       157 non-null    float64
 22  Glasses                      184 non-null    object
 23  Sex                          186 non-null    object
 24  Problems in last semester    186 non-null    object
 25  Coin                         186 non-null    object
 26  Rock paper scissors          186 non-null    object
 27  Animal                       186 non-null    object
 28  Month of birthday            186 non-null    int64
 29  Your rating in university    186 non-null    object
 30  Fastfood                     186 non-null    object
 31  Height of 5000 mm            186 non-null    int64
 32  Width of 5000 mm             186 non-null    int64
 33  Putin age                    186 non-null    int64
 34  Army                         186 non-null    object
 35  Hostel                       186 non-null    object
 36  Hair length                  186 non-null    float64
 37  Floor number                 186 non-null    int64
 38  Social network duration min  186 non-null    int64
 39  Chocolate                    186 non-null    object
 40  City population              186 non-null    float64
 41  Strange people               186 non-null    object
 42  Your insitute                186 non-null    object
 43  Brother-sister               186 non-null    object
 44  Plane seat                   186 non-null    object
 45  MIddle and index finger      186 non-null    int64
 46  Middle and ring finger       186 non-null    float64
 47  Middle and little finger     186 non-null    float64
dtypes: float64(7), int64(26), object(15)
memory usage: 69.9+ KB

In [ ]:
female=df[df['Sex']=='женский']
female.head()

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
0,20,170,40,2,2002,100,85,86,0,84,...,45,Сникерс,800000.0,Экономический,Математический и ИТ,нет ни брата ни сестры,У окна (пардон: у иллюминатора),20,10.0,40.0
3,19,168,38,2,2003,604,72,0,0,0,...,200,Баунти,900000.0,СоцГум,Юридический,есть сестра,У окна (пардон: у иллюминатора),12,13.5,35.0
4,23,159,36,1,1998,144,0,0,0,0,...,400,Баунти,860000.0,Педагогический,Педагогический,есть сестра,У окна (пардон: у иллюминатора),10,11.0,22.0
9,22,168,38,6,2000,297,71,5,0,0,...,40,Милки Вей,860.0,Математический и ИТ,СоцГум,есть брат,У окна (пардон: у иллюминатора),15,10.0,40.0
10,20,158,35,4,2001,1000,85,72,0,0,...,600,КитКат,800000.0,Педагогический,Естественный (биология-химия-физика-технари),есть и брат и сестра,У прохода,10,9.0,15.0

In [ ]:
male=df[df['Sex']=='мужской']
male.head()

,Age,Growth,Shoe size,Course number,Year of birth,Friend number,Russian rating,Maths rating,Physics rating,Computer science rating,...,Social network duration min,Chocolate,City population,Strange people,Your insitute,Brother-sister,Plane seat,MIddle and index finger,Middle and ring finger,Middle and little finger
1,22,191,43,7,2000,307,69,74,64,72,...,180,КитКат,800000.0,Математический и ИТ,Математический и ИТ,есть и брат и сестра,В середине,5,5.0,20.0
2,21,172,41,4,2000,186,78,62,0,0,...,90,КитКат,770000.0,Педагогический,Другое,есть брат,У окна (пардон: у иллюминатора),13,10.0,26.0
5,18,177,40,2,2003,100,70,68,0,75,...,250,Сникерс,1200000.0,СоцГум,Математический и ИТ,есть брат,У окна (пардон: у иллюминатора),12,7.0,30.0
6,18,180,42,0,2004,0,66,4,0,0,...,30,Сникерс,700000.0,Педагогический,Юридический,есть брат,У окна (пардон: у иллюминатора),5,30.0,35.0
7,19,180,48,1,2003,5,72,0,0,0,...,240,Баунти,880000.0,Естественный (биология-химия-физика-технари),Юридический,есть брат,У окна (пардон: у иллюминатора),7,5.0,25.0

In [ ]:
female['Weight'].mean()

np.float64(59.10526315789474)

In [ ]:
female['Weight']=female['Weight'].fillna(59.10526315789474)

/tmp/ipykernel_2802/868589053.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  female['Weight']=female['Weight'].fillna(59.10526315789474)

In [ ]:
male['Weight'].mean()

np.float64(71.58064516129032)

In [ ]:

male['Weight']=male['Weight'].fillna(71.58064516129032)

/tmp/ipykernel_2802/3198486544.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  male['Weight']=male['Weight'].fillna(71.58064516129032)

In [ ]:
df_new=pd.concat([male, female])
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 186 entries, 1 to 185
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          186 non-null    int64
 1   Growth                       186 non-null    int64
 2   Shoe size                    186 non-null    int64
 3   Course number                186 non-null    int64
 4   Year of birth                186 non-null    int64
 5   Friend number                186 non-null    int64
 6   Russian rating               186 non-null    int64
 7   Maths rating                 186 non-null    int64
 8   Physics rating               186 non-null    int64
 9   Computer science rating      186 non-null    int64
 10  Chemistry rating             186 non-null    int64
 11  Literature rating            186 non-null    int64
 12  History rating               186 non-null    int64
 13  Geography rating             186 non-null    int64
 14  Biology rating               186 non-null    int64
 15  Foreign language rating      186 non-null    int64
 16  Social science rating        186 non-null    int64
 17  Distance to home km          186 non-null    int64
 18  Minutes to first class       186 non-null    int64
 19  Children number              150 non-null    float64
 20  Removed teeth                148 non-null    float64
 21  Weight                       186 non-null    float64
 22  Glasses                      184 non-null    object
 23  Sex                          186 non-null    object
 24  Problems in last semester    186 non-null    object
 25  Coin                         186 non-null    object
 26  Rock paper scissors          186 non-null    object
 27  Animal                       186 non-null    object
 28  Month of birthday            186 non-null    int64
 29  Your rating in university    186 non-null    object
 30  Fastfood                     186 non-null    object
 31  Height of 5000 mm            186 non-null    int64
 32  Width of 5000 mm             186 non-null    int64
 33  Putin age                    186 non-null    int64
 34  Army                         186 non-null    object
 35  Hostel                       186 non-null    object
 36  Hair length                  186 non-null    float64
 37  Floor number                 186 non-null    int64
 38  Social network duration min  186 non-null    int64
 39  Chocolate                    186 non-null    object
 40  City population              186 non-null    float64
 41  Strange people               186 non-null    object
 42  Your insitute                186 non-null    object
 43  Brother-sister               186 non-null    object
 44  Plane seat                   186 non-null    object
 45  MIddle and index finger      186 non-null    int64
 46  Middle and ring finger       186 non-null    float64
 47  Middle and little finger     186 non-null    float64
dtypes: float64(7), int64(26), object(15)
memory usage: 71.2+ KB

In [ ]:
df_new['Weight'].mean()

np.float64(63.53201161071252)

In [ ]:
df2=pd.read_csv('/content/students.csv', delimiter=',')

In [ ]:
df2['Brother-sister'].value_counts()

Brother-sister
есть брат                 62
есть сестра               55
нет ни брата ни сестры    39
есть и брат и сестра      30
Name: count, dtype: int64

In [ ]:
singles=df2[df2['Brother-sister']=='все, у кого нет ни брата ни сестры']

In [ ]:
sublings=df2[df2['Brother-sister']!='нет ни брата ни сестры']

In [ ]:
singles['Children number'].median()

nan

In [ ]:
sublings['Children number'].median()

2.0

In [ ]:
singles['Children number']=singles['Children number'].fillna(0)

In [ ]:
sublings['Children number']=sublings['Children number'].fillna(2)

/tmp/ipykernel_2802/3802112258.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sublings['Children number']=sublings['Children number'].fillna(2)

In [ ]:
df_new2=pd.concat([singles, sublings])
df_new2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 147 entries, 1 to 184
Data columns (total 48 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Age                          147 non-null    int64
 1   Growth                       147 non-null    int64
 2   Shoe size                    147 non-null    int64
 3   Course number                147 non-null    int64
 4   Year of birth                147 non-null    int64
 5   Friend number                147 non-null    int64
 6   Russian rating               147 non-null    int64
 7   Maths rating                 147 non-null    int64
 8   Physics rating               147 non-null    int64
 9   Computer science rating      147 non-null    int64
 10  Chemistry rating             147 non-null    int64
 11  Literature rating            147 non-null    int64
 12  History rating               147 non-null    int64
 13  Geography rating             147 non-null    int64
 14  Biology rating               147 non-null    int64
 15  Foreign language rating      147 non-null    int64
 16  Social science rating        147 non-null    int64
 17  Distance to home km          147 non-null    int64
 18  Minutes to first class       147 non-null    int64
 19  Children number              147 non-null    float64
 20  Removed teeth                118 non-null    float64
 21  Weight                       129 non-null    float64
 22  Glasses                      146 non-null    object
 23  Sex                          147 non-null    object
 24  Problems in last semester    147 non-null    object
 25  Coin                         147 non-null    object
 26  Rock paper scissors          147 non-null    object
 27  Animal                       147 non-null    object
 28  Month of birthday            147 non-null    int64
 29  Your rating in university    147 non-null    object
 30  Fastfood                     147 non-null    object
 31  Height of 5000 mm            147 non-null    int64
 32  Width of 5000 mm             147 non-null    int64
 33  Putin age                    147 non-null    int64
 34  Army                         147 non-null    object
 35  Hostel                       147 non-null    object
 36  Hair length                  147 non-null    float64
 37  Floor number                 147 non-null    int64
 38  Social network duration min  147 non-null    int64
 39  Chocolate                    147 non-null    object
 40  City population              147 non-null    float64
 41  Strange people               147 non-null    object
 42  Your insitute                147 non-null    object
 43  Brother-sister               147 non-null    object
 44  Plane seat                   147 non-null    object
 45  MIddle and index finger      147 non-null    int64
 46  Middle and ring finger       147 non-null    float64
 47  Middle and little finger     147 non-null    float64
dtypes: float64(7), int64(26), object(15)
memory usage: 56.3+ KB

In [ ]:
df_new2['Children number'].median()

2.0