<a href="https://colab.research.google.com/github/Kristina-aut/For-example-Task-_dataset_studets/blob/main/%D0%A1%D1%80%D0%B0%D0%B2%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5_%D0%B2%D1%8B%D0%B3%D1%80%D1%83%D0%B7%D0%BA%D0%B8_%D0%B8%D0%B7_%D1%80%D0%B0%D0%B7%D0%BD%D1%8B%D1%85_%D0%B8%D1%81%D1%82%D0%BE%D1%87%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [10]:
df_01=pd.read_csv('/content/Входящие 01.csv', encoding='1251', delimiter=';')

In [6]:
df_02=pd.read_csv('/content/Входящие 02.csv', encoding='1251', delimiter=';')

In [7]:
df_03=pd.read_csv('/content/Входящие 03.csv', encoding='1251', delimiter=';')

In [8]:
import seaborn as sns
import matplotlib.pyplot as plt

In [11]:
df_01.head()

,Дата,Номер,Сумма,Статус,Примечание,Комментарий,Контрагент,ИНН/КПП,Организация,ИНН/КПП.1,...,Время,Тип пакета,Идентификатор пакета,Запущено в обработку,Получено контрагентом,Завершено,Увеличение суммы,НДС,Уменьшение суммы,НДС.1
0,30.09.21,БРН00709545,"4 056,46",Выполнение завершено успешно,NaN,"БРН00709545 на сумму 4 056,46р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,...,23:40:56,ДокОтгрВх,76210df0-7c48-4e6d-ad2b-6cbe2f3b7722,30.09.21 23:40,01.10.21 08:39,01.10.21 14:59,"0,00","0,00","0,00","0,00"
1,30.09.21,БРН00709545,"4 056,46",Выполнение завершено успешно,NaN,"БРН00709545 на сумму 4 056,46р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,...,23:40:56,ДокОтгрВх,76210df0-7c48-4e6d-ad2b-6cbe2f3b7722,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
2,30.09.21,БРН00709545,"0,00",Выполнение завершено успешно,NaN,"БРН00709545 на сумму 4 056,46р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,...,23:40:56,ДокОтгрВх,76210df0-7c48-4e6d-ad2b-6cbe2f3b7722,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
3,30.09.21,БРН00709520,"54 705,65",Выполнение завершено успешно,NaN,"БРН00709520 на сумму 54 705,65р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,...,23:34:51,ДокОтгрВх,1cfdcbd4-a43b-4543-90b6-59d0e6095b94,30.09.21 23:34,01.10.21 08:39,01.10.21 14:59,"0,00","0,00","0,00","0,00"
4,30.09.21,БРН00709520,"54 705,65",Выполнение завершено успешно,NaN,"БРН00709520 на сумму 54 705,65р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,...,23:34:51,ДокОтгрВх,1cfdcbd4-a43b-4543-90b6-59d0e6095b94,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"

In [12]:
pd.describe_option()

compute.use_bottleneck : bool
    Use the bottleneck library to accelerate if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
compute.use_numba : bool
    Use the numba engine option for select operations if it is installed,
    the default is False
    Valid values: False,True
    [default: False] [currently: False]
compute.use_numexpr : bool
    Use the numexpr library to accelerate computation if it is installed,
    the default is True
    Valid values: False,True
    [default: True] [currently: True]
display.chop_threshold : float or None
    if set to a float value, all float values smaller than the given threshold
    will be displayed as exactly 0 by repr and friends.
    [default: None] [currently: None]
display.colheader_justify : 'left'/'right'
    Controls the justification of column headers. used by DataFrameFormatter.
    [default: right] [currently: right]
display.date_dayfirst : boolean
    When True, prints and parses dates with the day first, eg 20/01/2005
    [default: False] [currently: False]
display.date_yearfirst : boolean
    When True, prints and parses dates with the year first, eg 2005/01/20
    [default: False] [currently: False]
display.encoding : str/unicode
    Defaults to the detected encoding of the console.
    Specifies the encoding to be used for strings returned by to_string,
    these are generally strings meant to be displayed on the console.
    [default: UTF-8] [currently: UTF-8]
display.expand_frame_repr : boolean
    Whether to print out the full DataFrame repr for wide DataFrames across
    multiple lines, `max_columns` is still respected, but the output will
    wrap-around across multiple "pages" if its width exceeds `display.width`.
    [default: True] [currently: True]
display.float_format : callable
    The callable should accept a floating point number and return
    a string with the desired format of the number. This is used
    in some places like SeriesFormatter.
    See formats.format.EngFormatter for an example.
    [default: None] [currently: None]
display.html.border : int
    A ``border=value`` attribute is inserted in the ``<table>`` tag
    for the DataFrame HTML repr.
    [default: 1] [currently: 1]
display.html.table_schema : boolean
    Whether to publish a Table Schema representation for frontends
    that support it.
    (default: False)
    [default: False] [currently: False]
display.html.use_mathjax : boolean
    When True, Jupyter notebook will process table contents using MathJax,
    rendering mathematical expressions enclosed by the dollar symbol.
    (default: True)
    [default: True] [currently: True]
display.large_repr : 'truncate'/'info'
    For DataFrames exceeding max_rows/max_cols, the repr (and HTML repr) can
    show a truncated table, or switch to the view from
    df.info() (the behaviour in earlier versions of pandas).
    [default: truncate] [currently: truncate]
display.max_categories : int
    This sets the maximum number of categories pandas should output when
    printing out a `Categorical` or a Series of dtype "category".
    [default: 8] [currently: 8]
display.max_columns : int
    If max_cols is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 or None and pandas will auto-detect
    the width of the terminal and print a truncated object which fits
    the screen width. The IPython notebook, IPython qtconsole, or IDLE
    do not run in a terminal and hence it is not possible to do
    correct auto-detection and defaults to 20.
    [default: 20] [currently: 20]
display.max_colwidth : int or None
    The maximum width in characters of a column in the repr of
    a pandas data structure. When the column overflows, a "..."
    placeholder is embedded in the output. A 'None' value means unlimited.
    [default: 50] [currently: 50]
display.max_dir_items : int
    The number of items that will be added to `dir(...)`. 'None' value means
    unlimited. Because dir is cached, changing this option will not immediately
    affect already existing dataframes until a column is deleted or added.

    This is for instance used to suggest columns from a dataframe to tab
    completion.
    [default: 100] [currently: 100]
display.max_info_columns : int
    max_info_columns is used in DataFrame.info method to decide if
    per column information will be printed.
    [default: 100] [currently: 100]
display.max_info_rows : int
    df.info() will usually show null-counts for each column.
    For large frames this can be quite slow. max_info_rows and max_info_cols
    limit this null check only to frames with smaller dimensions than
    specified.
    [default: 1690785] [currently: 1690785]
display.max_rows : int
    If max_rows is exceeded, switch to truncate view. Depending on
    `large_repr`, objects are either centrally truncated or printed as
    a summary view. 'None' value means unlimited.

    In case python/IPython is running in a terminal and `large_repr`
    equals 'truncate' this can be set to 0 and pandas will auto-detect
    the height of the terminal and print a truncated object which fits
    the screen height. The IPython notebook, IPython qtconsole, or
    IDLE do not run in a terminal and hence it is not possible to do
    correct auto-detection.
    [default: 60] [currently: 60]
display.max_seq_items : int or None
    When pretty-printing a long sequence, no more then `max_seq_items`
    will be printed. If items are omitted, they will be denoted by the
    addition of "..." to the resulting string.

    If set to None, the number of items to be printed is unlimited.
    [default: 100] [currently: 100]
display.memory_usage : bool, string or None
    This specifies if the memory usage of a DataFrame should be displayed when
    df.info() is called. Valid values True,False,'deep'
    [default: True] [currently: True]
display.min_rows : int
    The numbers of rows to show in a truncated view (when `max_rows` is
    exceeded). Ignored when `max_rows` is set to None or 0. When set to
    None, follows the value of `max_rows`.
    [default: 10] [currently: 10]
display.multi_sparse : boolean
    "sparsify" MultiIndex display (don't display repeated
    elements in outer levels within groups)
    [default: True] [currently: True]
display.notebook_repr_html : boolean
    When True, IPython notebook will use html representation for
    pandas objects (if it is available).
    [default: True] [currently: True]
display.pprint_nest_depth : int
    Controls the number of nested levels to process when pretty-printing
    [default: 3] [currently: 3]
display.precision : int
    Floating point output precision in terms of number of places after the
    decimal, for regular formatting as well as scientific notation. Similar
    to ``precision`` in :meth:`numpy.set_printoptions`.
    [default: 6] [currently: 6]
display.show_dimensions : boolean or 'truncate'
    Whether to print out dimensions at the end of DataFrame repr.
    If 'truncate' is specified, only print out the dimensions if the
    frame is truncated (e.g. not display all rows and/or columns)
    [default: truncate] [currently: truncate]
display.unicode.ambiguous_as_wide : boolean
    Whether to use the Unicode East Asian Width to calculate the display text
    width.
    Enabling this may affect to the performance (default: False)
    [default: False] [currently: False]
display.unicode.east_asian_width : boolean
    Whether to use the Unicode East Asian Width to calculate the display text
    width.
    Enabling this may affect to the performance (default: False)
    [default: False] [currently: False]
display.width : int
    Width of the display in characters. In case python/IPython is running in
    a terminal this can be set to None and pandas will correctly auto-detect
    the width.
    Note that the IPython notebook, IPython qtconsole, or IDLE do not run in a
    terminal and hence it is not possible to correctly detect the width.
    [default: 80] [currently: 80]
future.infer_string Whether to infer sequence of str objects as pyarrow string dtype, which will be the default in pandas 3.0 (at which point this option will be deprecated).
    [default: False] [currently: False]
future.no_silent_downcasting Whether to opt-in to the future behavior which will *not* silently downcast results from Series and DataFrame `where`, `mask`, and `clip` methods. Silent downcasting will be removed in pandas 3.0 (at which point this option will be deprecated).
    [default: False] [currently: False]
io.excel.ods.reader : string
    The default Excel reader engine for 'ods' files. Available options:
    auto, odf, calamine.
    [default: auto] [currently: auto]
io.excel.ods.writer : string
    The default Excel writer engine for 'ods' files. Available options:
    auto, odf.
    [default: auto] [currently: auto]
io.excel.xls.reader : string
    The default Excel reader engine for 'xls' files. Available options:
    auto, xlrd, calamine.
    [default: auto] [currently: auto]
io.excel.xlsb.reader : string
    The default Excel reader engine for 'xlsb' files. Available options:
    auto, pyxlsb, calamine.
    [default: auto] [currently: auto]
io.excel.xlsm.reader : string
    The default Excel reader engine for 'xlsm' files. Available options:
    auto, xlrd, openpyxl, calamine.
    [default: auto] [currently: auto]
io.excel.xlsm.writer : string
    The default Excel writer engine for 'xlsm' files. Available options:
    auto, openpyxl.
    [default: auto] [currently: auto]
io.excel.xlsx.reader : string
    The default Excel reader engine for 'xlsx' files. Available options:
    auto, xlrd, openpyxl, calamine.
    [default: auto] [currently: auto]
io.excel.xlsx.writer : string
    The default Excel writer engine for 'xlsx' files. Available options:
    auto, openpyxl, xlsxwriter.
    [default: auto] [currently: auto]
io.hdf.default_format : format
    default format writing format, if None, then
    put will default to 'fixed' and append will default to 'table'
    [default: None] [currently: None]
io.hdf.dropna_table : boolean
    drop ALL nan rows when appending to a table
    [default: False] [currently: False]
io.parquet.engine : string
    The default parquet reader/writer engine. Available options:
    'auto', 'pyarrow', 'fastparquet', the default is 'auto'
    [default: auto] [currently: auto]
io.sql.engine : string
    The default sql reader/writer engine. Available options:
    'auto', 'sqlalchemy', the default is 'auto'
    [default: auto] [currently: auto]
mode.chained_assignment : string
    Raise an exception, warn, or no action if trying to use chained assignment,
    The default is warn
    [default: warn] [currently: warn]
mode.copy_on_write : bool
    Use new copy-view behaviour using Copy-on-Write. Defaults to False,
    unless overridden by the 'PANDAS_COPY_ON_WRITE' environment variable
    (if set to "1" for True, needs to be set before pandas is imported).
    [default: False] [currently: False]
mode.data_manager : string
    Internal data manager type; can be "block" or "array". Defaults to "block",
    unless overridden by the 'PANDAS_DATA_MANAGER' environment variable (needs
    to be set before pandas is imported).
    [default: block] [currently: block]
    (Deprecated, use `` instead.)
mode.sim_interactive : boolean
    Whether to simulate interactive mode for purposes of testing
    [default: False] [currently: False]
mode.string_storage : string
    The default storage for StringDtype. This option is ignored if
    ``future.infer_string`` is set to True.
    [default: python] [currently: python]
mode.use_inf_as_na : boolean
    True means treat None, NaN, INF, -INF as NA (old way),
    False means None and NaN are null, but INF, -INF are not NA
    (new way).

    This option is deprecated in pandas 2.1.0 and will be removed in 3.0.
    [default: False] [currently: False]
    (Deprecated, use `` instead.)
plotting.backend : str
    The plotting backend to use. The default value is "matplotlib", the
    backend provided with pandas. Other backends can be specified by
    providing the name of the module that implements the backend.
    [default: matplotlib] [currently: matplotlib]
plotting.matplotlib.register_converters : bool or 'auto'.
    Whether to register converters with matplotlib's units registry for
    dates, times, datetimes, and Periods. Toggling to False will remove
    the converters, restoring any converters that pandas overwrote.
    [default: auto] [currently: auto]
styler.format.decimal : str
    The character representation for the decimal separator for floats and complex.
    [default: .] [currently: .]
styler.format.escape : str, optional
    Whether to escape certain characters according to the given context; html or latex.
    [default: None] [currently: None]
styler.format.formatter : str, callable, dict, optional
    A formatter object to be used as default within ``Styler.format``.
    [default: None] [currently: None]
styler.format.na_rep : str, optional
    The string representation for values identified as missing.
    [default: None] [currently: None]
styler.format.precision : int
    The precision for floats and complex numbers.
    [default: 6] [currently: 6]
styler.format.thousands : str, optional
    The character representation for thousands separator for floats, int and complex.
    [default: None] [currently: None]
styler.html.mathjax : bool
    If False will render special CSS classes to table attributes that indicate Mathjax
    will not be used in Jupyter Notebook.
    [default: True] [currently: True]
styler.latex.environment : str
    The environment to replace ``\begin{table}``. If "longtable" is used results
    in a specific longtable environment format.
    [default: None] [currently: None]
styler.latex.hrules : bool
    Whether to add horizontal rules on top and bottom and below the headers.
    [default: False] [currently: False]
styler.latex.multicol_align : {"r", "c", "l", "naive-l", "naive-r"}
    The specifier for horizontal alignment of sparsified LaTeX multicolumns. Pipe
    decorators can also be added to non-naive values to draw vertical
    rules, e.g. "\|r" will draw a rule on the left side of right aligned merged cells.
    [default: r] [currently: r]
styler.latex.multirow_align : {"c", "t", "b"}
    The specifier for vertical alignment of sparsified LaTeX multirows.
    [default: c] [currently: c]
styler.render.encoding : str
    The encoding used for output HTML and LaTeX files.
    [default: utf-8] [currently: utf-8]
styler.render.max_columns : int, optional
    The maximum number of columns that will be rendered. May still be reduced to
    satisfy ``max_elements``, which takes precedence.
    [default: None] [currently: None]
styler.render.max_elements : int
    The maximum number of data-cell (<td>) elements that will be rendered before
    trimming will occur over columns, rows or both if needed.
    [default: 262144] [currently: 262144]
styler.render.max_rows : int, optional
    The maximum number of rows that will be rendered. May still be reduced to
    satisfy ``max_elements``, which takes precedence.
    [default: None] [currently: None]
styler.render.repr : str
    Determine which output to use in Jupyter Notebook in {"html", "latex"}.
    [default: html] [currently: html]
styler.sparse.columns : bool
    Whether to sparsify the display of hierarchical columns. Setting to False will
    display each explicit level element in a hierarchical key for each column.
    [default: True] [currently: True]
styler.sparse.index : bool
    Whether to sparsify the display of a hierarchical index. Setting to False will
    display each explicit level element in a hierarchical key for each row.
    [default: True] [currently: True]

In [13]:
pd.get_option('display.max_columns')

20

In [14]:
pd.set_option('display.max_columns', 40)

In [15]:
df_01.head()

,Дата,Номер,Сумма,Статус,Примечание,Комментарий,Контрагент,ИНН/КПП,Организация,ИНН/КПП.1,Тип документа,Имя файла,Дата.1,Номер.1,Сумма.1,Сумма НДС,Ответственный,Подразделение,Код,Дата.2,Время,Тип пакета,Идентификатор пакета,Запущено в обработку,Получено контрагентом,Завершено,Увеличение суммы,НДС,Уменьшение суммы,НДС.1
0,30.09.21,БРН00709545,"4 056,46",Выполнение завершено успешно,NaN,"БРН00709545 на сумму 4 056,46р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,ЭДОНакл,DP_TOVTORGPR_2BE911035223f7011e2addf0050569171...,30.09.21,БРН00709545,"4 056,46","368,77",NaN,Аптека №1,3,30.09.21,23:40:56,ДокОтгрВх,76210df0-7c48-4e6d-ad2b-6cbe2f3b7722,30.09.21 23:40,01.10.21 08:39,01.10.21 14:59,"0,00","0,00","0,00","0,00"
1,30.09.21,БРН00709545,"4 056,46",Выполнение завершено успешно,NaN,"БРН00709545 на сумму 4 056,46р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,СчФктр,ON_NSCHFDOPPR_2BE911035223f7011e2addf005056917...,30.09.21,БРН00709545,"4 056,46","368,77",NaN,Аптека №1,3,30.09.21,23:40:56,ДокОтгрВх,76210df0-7c48-4e6d-ad2b-6cbe2f3b7722,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
2,30.09.21,БРН00709545,"0,00",Выполнение завершено успешно,NaN,"БРН00709545 на сумму 4 056,46р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,ЭДОРеестрСертификатов,SE_RSERT_3255510243325701001_40254198734025010...,NaN,NaN,"0,00","0,00",NaN,Аптека №1,3,30.09.21,23:40:56,ДокОтгрВх,76210df0-7c48-4e6d-ad2b-6cbe2f3b7722,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
3,30.09.21,БРН00709520,"54 705,65",Выполнение завершено успешно,NaN,"БРН00709520 на сумму 54 705,65р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,ЭДОНакл,DP_TOVTORGPR_2BE911035223f7011e2addf0050569171...,30.09.21,БРН00709520,"54 705,65","4 973,27",NaN,Аптека №2,6,30.09.21,23:34:51,ДокОтгрВх,1cfdcbd4-a43b-4543-90b6-59d0e6095b94,30.09.21 23:34,01.10.21 08:39,01.10.21 14:59,"0,00","0,00","0,00","0,00"
4,30.09.21,БРН00709520,"54 705,65",Выполнение завершено успешно,NaN,"БРН00709520 на сумму 54 705,65р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,СчФктр,ON_NSCHFDOPPR_2BE911035223f7011e2addf005056917...,30.09.21,БРН00709520,"54 705,65","4 973,27",NaN,Аптека №2,6,30.09.21,23:34:51,ДокОтгрВх,1cfdcbd4-a43b-4543-90b6-59d0e6095b94,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"

In [16]:
df_02.head()

,Дата,Номер,Сумма,Статус,Примечание,Комментарий,Контрагент,ИНН/КПП,Организация,ИНН/КПП.1,Тип документа,Имя файла,Дата.1,Номер.1,Сумма.1,Сумма НДС,Ответственный,Подразделение,Код,Дата.2,Время,Тип пакета,Идентификатор пакета,Запущено в обработку,Получено контрагентом,Завершено,Увеличение суммы,НДС,Уменьшение суммы,НДС.1
0,09.12.20,10324858-30,"417,34",Выполнение завершено успешно,NaN,Интернет заказ: MA-18962181; Интернет заказ: M...,"Филиал АО НПК ""Катрен"" в г. Химки",5408130693 / 504743001,ООО Рога и Копыта,4025419873 / 402501001,УпдДоп,ON_NSCHFDOPPR_2BE911035223f7011e2addf005056917...,09.12.20,10324858-30,"417,34","37,94",NaN,Аптека №6,8,09.12.20,11:05:06,ДокОтгрВх,90e7b521-7842-42a7-a55f-876cf0aec0e1,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
1,09.12.20,10324858-30,"0,00",Выполнение завершено успешно,NaN,Интернет заказ: MA-18962181; Интернет заказ: M...,"Филиал АО НПК ""Катрен"" в г. Химки",5408130693 / 504743001,ООО Рога и Копыта,4025419873 / 402501001,ЭДОРеестрСертификатов,SE_RSERT_2BE911035223f7011e2addf005056917125_2...,NaN,NaN,"0,00","0,00",NaN,Аптека №6,8,09.12.20,11:05:06,ДокОтгрВх,90e7b521-7842-42a7-a55f-876cf0aec0e1,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
2,09.12.20,10324858-30,"0,00",Выполнение завершено успешно,NaN,Интернет заказ: MA-18962181; Интернет заказ: M...,"Филиал АО НПК ""Катрен"" в г. Химки",5408130693 / 504743001,ООО Рога и Копыта,4025419873 / 402501001,NaN,Список КИЗов.pdf,NaN,NaN,"0,00","0,00",NaN,Аптека №6,8,09.12.20,11:05:06,ДокОтгрВх,90e7b521-7842-42a7-a55f-876cf0aec0e1,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
3,09.12.20,10324216-30,"1 952,73",Выполнение завершено успешно,NaN,Интернет заказ: MI-18944644; Интернет заказ: M...,"Филиал АО НПК ""Катрен"" в г. Химки",5408130693 / 504743001,ООО Рога и Копыта,4025419873 / 402501001,СчФктр,ON_NSCHFDOPPR_2BE911035223f7011e2addf005056917...,09.12.20,10324216-30,"1 952,73","177,52",NaN,Аптека №7,9,09.12.20,10:35:55,ДокОтгрВх,4472a6b6-f72a-4dc4-8566-5d3a6336b4e2,09.12.20 10:35,09.12.20 10:39,10.12.20 10:25,"0,00","0,00","0,00","0,00"
4,09.12.20,10324216-30,"0,00",Выполнение завершено успешно,NaN,Интернет заказ: MI-18944644; Интернет заказ: M...,"Филиал АО НПК ""Катрен"" в г. Химки",5408130693 / 504743001,ООО Рога и Копыта,4025419873 / 402501001,ПротЦен,ON_PROTCEN_2BE911035223f7011e2addf005056917125...,09.12.20,NaN,"0,00","0,00",NaN,Аптека №7,9,09.12.20,10:35:55,ДокОтгрВх,4472a6b6-f72a-4dc4-8566-5d3a6336b4e2,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"

In [25]:
df_03.tail()

,Дата,Номер,Сумма,Статус,Примечание,Комментарий,Контрагент,ИНН/КПП,Организация,ИНН/КПП.1,Тип документа,Имя файла,Дата.1,Номер.1,Сумма.1,Сумма НДС,Ответственный,Подразделение,Код,Дата.2,Время,Тип пакета,Идентификатор пакета,Запущено в обработку,Получено контрагентом,Завершено,Увеличение суммы,НДС,Уменьшение суммы,НДС.1
95732,01.10.18,18-0-971380,"8 992,66",Выполнение завершено успешно,NaN,NaN,"ФК Гранд Капитал, ООО",7729418511 / 771401001,ООО Рога и Копыта,4025419873 / 402501001,УпдСчфДоп,ON_SCHFDOPPR_2BE911035223f7011e2addf0050569171...,01.10.18,18-0-971380,"8 992,66","892,07",NaN,Аптека №4,7,01.10.18,00:04:20,ДокОтгрВх,08123bc2-8ef1-43c5-a6ab-9f5d14e7c644,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
95733,01.10.18,18-0-971380,"0,00",Выполнение завершено успешно,NaN,NaN,"ФК Гранд Капитал, ООО",7729418511 / 771401001,ООО Рога и Копыта,4025419873 / 402501001,ЭДОРеестрСертификатов,SE_RSERT_4025419873402501001_77294185117714010...,NaN,NaN,"0,00","0,00",NaN,Аптека №4,7,01.10.18,00:04:20,ДокОтгрВх,08123bc2-8ef1-43c5-a6ab-9f5d14e7c644,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
95734,01.10.18,18-0-970909,"0,00",Выполнение завершено успешно,NaN,NaN,"ФК Гранд Капитал, ООО",7729418511 / 771401001,ООО Рога и Копыта,4025419873 / 402501001,ПротЦен,ON_PROTCEN_4025419873402501001_KKKK_7729418511...,01.10.18,NaN,"0,00","0,00",NaN,Аптека №7,9,01.10.18,00:04:01,ДокОтгрВх,c1bba12a-d3ef-4709-b48a-c65cfa2ea588,01.10.18 00:03,01.10.18 12:33,01.10.18 13:12,"0,00","0,00","0,00","0,00"
95735,01.10.18,18-0-970909,"14 242,73",Выполнение завершено успешно,NaN,NaN,"ФК Гранд Капитал, ООО",7729418511 / 771401001,ООО Рога и Копыта,4025419873 / 402501001,УпдСчфДоп,ON_SCHFDOPPR_2BE911035223f7011e2addf0050569171...,01.10.18,18-0-970909,"14 242,73","1 331,84",NaN,Аптека №7,9,01.10.18,00:04:01,ДокОтгрВх,c1bba12a-d3ef-4709-b48a-c65cfa2ea588,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
95736,01.10.18,18-0-970909,"0,00",Выполнение завершено успешно,NaN,NaN,"ФК Гранд Капитал, ООО",7729418511 / 771401001,ООО Рога и Копыта,4025419873 / 402501001,ЭДОРеестрСертификатов,SE_RSERT_4025419873402501001_77294185117714010...,NaN,NaN,"0,00","0,00",NaN,Аптека №7,9,01.10.18,00:04:01,ДокОтгрВх,c1bba12a-d3ef-4709-b48a-c65cfa2ea588,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"

In [85]:
df_03.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 95737 entries, 0 to 95736
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Дата                   95737 non-null  object
 1   Номер                  95737 non-null  object
 2   Сумма                  95737 non-null  object
 3   Статус                 95737 non-null  object
 4   Примечание             0 non-null      float64
 5   Комментарий            28812 non-null  object
 6   Контрагент             95737 non-null  object
 7   ИНН/КПП                95737 non-null  object
 8   Организация            95737 non-null  object
 9   ИНН/КПП.1              95737 non-null  object
 10  Тип документа          93465 non-null  object
 11  Имя файла              95737 non-null  object
 12  Дата.1                 67383 non-null  object
 13  Номер.1                49425 non-null  object
 14  Сумма.1                95737 non-null  object
 15  Сумма НДС              95737 non-null  object
 16  Ответственный          0 non-null      float64
 17  Подразделение          95737 non-null  object
 18  Код                    95737 non-null  int64
 19  Дата.2                 95737 non-null  object
 20  Время                  95737 non-null  object
 21  Тип пакета             95737 non-null  object
 22  Идентификатор пакета   95737 non-null  object
 23  Запущено в обработку   27190 non-null  object
 24  Получено контрагентом  27172 non-null  object
 25  Завершено              27165 non-null  object
 26  Увеличение суммы       95737 non-null  object
 27  НДС                    95737 non-null  object
 28  Уменьшение суммы       95737 non-null  object
 29  НДС.1                  95737 non-null  object
dtypes: float64(2), int64(1), object(27)
memory usage: 21.9+ MB

In [26]:
result=pd.concat([df_01, df_02, df_03], axis=0)

In [29]:
result.head(25)

,Дата,Номер,Сумма,Статус,Примечание,Комментарий,Контрагент,ИНН/КПП,Организация,ИНН/КПП.1,Тип документа,Имя файла,Дата.1,Номер.1,Сумма.1,Сумма НДС,Ответственный,Подразделение,Код,Дата.2,Время,Тип пакета,Идентификатор пакета,Запущено в обработку,Получено контрагентом,Завершено,Увеличение суммы,НДС,Уменьшение суммы,НДС.1
0,30.09.21,БРН00709545,"4 056,46",Выполнение завершено успешно,NaN,"БРН00709545 на сумму 4 056,46р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,ЭДОНакл,DP_TOVTORGPR_2BE911035223f7011e2addf0050569171...,30.09.21,БРН00709545,"4 056,46","368,77",NaN,Аптека №1,3,30.09.21,23:40:56,ДокОтгрВх,76210df0-7c48-4e6d-ad2b-6cbe2f3b7722,30.09.21 23:40,01.10.21 08:39,01.10.21 14:59,"0,00","0,00","0,00","0,00"
1,30.09.21,БРН00709545,"4 056,46",Выполнение завершено успешно,NaN,"БРН00709545 на сумму 4 056,46р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,СчФктр,ON_NSCHFDOPPR_2BE911035223f7011e2addf005056917...,30.09.21,БРН00709545,"4 056,46","368,77",NaN,Аптека №1,3,30.09.21,23:40:56,ДокОтгрВх,76210df0-7c48-4e6d-ad2b-6cbe2f3b7722,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
2,30.09.21,БРН00709545,"0,00",Выполнение завершено успешно,NaN,"БРН00709545 на сумму 4 056,46р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,ЭДОРеестрСертификатов,SE_RSERT_3255510243325701001_40254198734025010...,NaN,NaN,"0,00","0,00",NaN,Аптека №1,3,30.09.21,23:40:56,ДокОтгрВх,76210df0-7c48-4e6d-ad2b-6cbe2f3b7722,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
3,30.09.21,БРН00709520,"54 705,65",Выполнение завершено успешно,NaN,"БРН00709520 на сумму 54 705,65р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,ЭДОНакл,DP_TOVTORGPR_2BE911035223f7011e2addf0050569171...,30.09.21,БРН00709520,"54 705,65","4 973,27",NaN,Аптека №2,6,30.09.21,23:34:51,ДокОтгрВх,1cfdcbd4-a43b-4543-90b6-59d0e6095b94,30.09.21 23:34,01.10.21 08:39,01.10.21 14:59,"0,00","0,00","0,00","0,00"
4,30.09.21,БРН00709520,"54 705,65",Выполнение завершено успешно,NaN,"БРН00709520 на сумму 54 705,65р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,СчФктр,ON_NSCHFDOPPR_2BE911035223f7011e2addf005056917...,30.09.21,БРН00709520,"54 705,65","4 973,27",NaN,Аптека №2,6,30.09.21,23:34:51,ДокОтгрВх,1cfdcbd4-a43b-4543-90b6-59d0e6095b94,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
5,30.09.21,БРН00709520,"0,00",Выполнение завершено успешно,NaN,"БРН00709520 на сумму 54 705,65р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,ЭДОРеестрСертификатов,SE_RSERT_3255510243325701001_40254198734025010...,NaN,NaN,"0,00","0,00",NaN,Аптека №2,6,30.09.21,23:34:51,ДокОтгрВх,1cfdcbd4-a43b-4543-90b6-59d0e6095b94,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
6,30.09.21,БРН00709520,"0,00",Выполнение завершено успешно,NaN,"БРН00709520 на сумму 54 705,65р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,ПротЦен,ON_PROTCEN__20210930_cf4dcf0a-222d-11ec-b9bc-0...,30.09.21,NaN,"0,00","0,00",NaN,Аптека №2,6,30.09.21,23:34:51,ДокОтгрВх,1cfdcbd4-a43b-4543-90b6-59d0e6095b94,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
7,30.09.21,БРН00709519,"5 890,95",Выполнение завершено успешно,NaN,"БРН00709519 на сумму 5 890,95р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,ЭДОНакл,DP_TOVTORGPR_2BE911035223f7011e2addf0050569171...,30.09.21,БРН00709519,"5 890,95","490,76",NaN,Аптека №2,6,30.09.21,23:34:51,ДокОтгрВх,cc4356f7-1ded-4244-9eb0-588be6c8d99c,30.09.21 23:34,01.10.21 08:38,01.10.21 14:59,"0,00","0,00","0,00","0,00"
8,30.09.21,БРН00709519,"5 890,95",Выполнение завершено успешно,NaN,"БРН00709519 на сумму 5 890,95р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,СчФктр,ON_NSCHFDOPPR_2BE911035223f7011e2addf005056917...,30.09.21,БРН00709519,"5 890,95","490,76",NaN,Аптека №2,6,30.09.21,23:34:51,ДокОтгрВх,cc4356f7-1ded-4244-9eb0-588be6c8d99c,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
9,30.09.21,БРН00709519,"0,00",Выполнение завершено успешно,NaN,"БРН00709519 на сумму 5 890,95р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,ЭДОРеестрСертификатов,SE_RSERT_3255510243325701001_40254198734025010...,NaN,NaN,"0,00","0,00",NaN,Аптека №2,6,30.09.21,23:34:51,ДокОтгрВх,cc4356f7-1ded-4244-9eb0-588be6c8d99c,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
10,30.09.21,БРН00709519,"0,00",Выполнение завершено успешно,NaN,"БРН00709519 на сумму 5 890,95р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,ПротЦен,ON_PROTCEN__20210930_cf4dcf07-222d-11ec-b9bc-0...,30.09.21,NaN,"0,00","0,00",NaN,Аптека №2,6,30.09.21,23:34:51,ДокОтгрВх,cc4356f7-1ded-4244-9eb0-588be6c8d99c,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
11,30.09.21,БРН00709497,"1 141,24",Выполнение завершено успешно,NaN,"БРН00709497 на сумму 1 141,24р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,ЭДОНакл,DP_TOVTORGPR_2BE911035223f7011e2addf0050569171...,30.09.21,БРН00709497,"1 141,24","103,75",NaN,Аптека №1,3,30.09.21,23:28:52,ДокОтгрВх,bb031889-fd99-44d2-8302-9cba40a9bbd5,30.09.21 23:28,01.10.21 08:38,01.10.21 14:59,"0,00","0,00","0,00","0,00"
12,30.09.21,БРН00709497,"1 141,24",Выполнение завершено успешно,NaN,"БРН00709497 на сумму 1 141,24р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,СчФктр,ON_NSCHFDOPPR_2BE911035223f7011e2addf005056917...,30.09.21,БРН00709497,"1 141,24","103,75",NaN,Аптека №1,3,30.09.21,23:28:52,ДокОтгрВх,bb031889-fd99-44d2-8302-9cba40a9bbd5,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
13,30.09.21,БРН00709497,"0,00",Выполнение завершено успешно,NaN,"БРН00709497 на сумму 1 141,24р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,ЭДОРеестрСертификатов,SE_RSERT_3255510243325701001_40254198734025010...,NaN,NaN,"0,00","0,00",NaN,Аптека №1,3,30.09.21,23:28:52,ДокОтгрВх,bb031889-fd99-44d2-8302-9cba40a9bbd5,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
14,30.09.21,БРН00709497,"0,00",Выполнение завершено успешно,NaN,"БРН00709497 на сумму 1 141,24р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,ПротЦен,ON_PROTCEN__20210930_e793c8d5-222c-11ec-b9bc-0...,30.09.21,NaN,"0,00","0,00",NaN,Аптека №1,3,30.09.21,23:28:52,ДокОтгрВх,bb031889-fd99-44d2-8302-9cba40a9bbd5,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
15,30.09.21,БРН00709476,"5 822,85",Выполнение завершено успешно,NaN,"БРН00709476 на сумму 5 822,85р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,ЭДОНакл,DP_TOVTORGPR_2BE911035223f7011e2addf0050569171...,30.09.21,БРН00709476,"5 822,85","529,35",NaN,Аптечный пункт №3,16,30.09.21,23:28:43,ДокОтгрВх,f5791b2f-4b03-49f2-96b0-31c1d7aef12e,30.09.21 23:28,01.10.21 08:38,01.10.21 14:59,"0,00","0,00","0,00","0,00"
16,30.09.21,БРН00709476,"5 822,85",Выполнение завершено успешно,NaN,"БРН00709476 на сумму 5 822,85р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,СчФктр,ON_NSCHFDOPPR_2BE911035223f7011e2addf005056917...,30.09.21,БРН00709476,"5 822,85","529,35",NaN,Аптечный пункт №3,16,30.09.21,23:28:43,ДокОтгрВх,f5791b2f-4b03-49f2-96b0-31c1d7aef12e,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
17,30.09.21,БРН00709476,"0,00",Выполнение завершено успешно,NaN,"БРН00709476 на сумму 5 822,85р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,ЭДОРеестрСертификатов,SE_RSERT_3255510243325701001_40254198734025010...,NaN,NaN,"0,00","0,00",NaN,Аптечный пункт №3,16,30.09.21,23:28:43,ДокОтгрВх,f5791b2f-4b03-49f2-96b0-31c1d7aef12e,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
18,30.09.21,БРН00709476,"0,00",Выполнение завершено успешно,NaN,"БРН00709476 на сумму 5 822,85р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,ПротЦен,ON_PROTCEN__20210930_9aad2b8c-222c-11ec-b9bc-0...,30.09.21,NaN,"0,00","0,00",NaN,Аптечный пункт №3,16,30.09.21,23:28:43,ДокОтгрВх,f5791b2f-4b03-49f2-96b0-31c1d7aef12e,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
19,30.09.21,БРН00709475,"1 693,90",Выполнение завершено успешно,NaN,"БРН00709475 на сумму 1 693,9р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,ЭДОНакл,DP_TOVTORGPR_2BE911035223f7011e2addf0050569171...,30.09.21,БРН00709475,"1 693,90","282,32",NaN,Аптечный пункт №3,16,30.09.21,23:28:43,ДокОтгрВх,854ee468-0f41-4369-9d7b-a4c10668291d,30.09.21 23:28,01.10.21 08:38,01.10.21 14:59,"0,00","0,00","0,00","0,00"
20,30.09.21,БРН00709475,"1 693,90",Выполнение завершено успешно,NaN,"БРН00709475 на сумму 1 693,9р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,СчФктр,ON_NSCHFDOPPR_2BE911035223f7011e2addf005056917...,30.09.21,БРН00709475,"1 693,90","282,32",NaN,Аптечный пункт №3,16,30.09.21,23:28:43,ДокОтгрВх,854ee468-0f41-4369-9d7b-a4c10668291d,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
21,30.09.21,БРН00709475,"0,00",Выполнение завершено успешно,NaN,"БРН00709475 на сумму 1 693,9р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,ЭДОРеестрСертификатов,SE_RSERT_3255510243325701001_40254198734025010...,NaN,NaN,"0,00","0,00",NaN,Аптечный пункт №3,16,30.09.21,23:28:43,ДокОтгрВх,854ee468-0f41-4369-9d7b-a4c10668291d,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
22,30.09.21,БРН00709466,"4 481,92",Выполнение завершено успешно,NaN,"БРН00709466 на сумму 4 481,92р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,ЭДОНакл,DP_TOVTORGPR_2BE911035223f7011e2addf0050569171...,30.09.21,БРН00709466,"4 481,92","407,45",NaN,Аптека №6,8,30.09.21,23:25:48,ДокОтгрВх,29720852-bb90-4ce0-8123-63218ccfcd41,30.09.21 23:25,01.10.21 08:38,01.10.21 14:59,"0,00","0,00","0,00","0,00"
23,30.09.21,БРН00709466,"4 481,92",Выполнение завершено успешно,NaN,"БРН00709466 на сумму 4 481,92р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,СчФктр,ON_NSCHFDOPPR_2BE911035223f7011e2addf005056917...,30.09.21,БРН00709466,"4 481,92","407,45",NaN,Аптека №6,8,30.09.21,23:25:48,ДокОтгрВх,29720852-bb90-4ce0-8123-63218ccfcd41,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"
24,30.09.21,БРН00709466,"0,00",Выполнение завершено успешно,NaN,"БРН00709466 на сумму 4 481,92р.","Пульс Брянск, ООО",3255510243 / 325701001,ООО Рога и Копыта,4025419873 / 402501001,ЭДОРеестрСертификатов,SE_RSERT_3255510243325701001_40254198734025010...,NaN,NaN,"0,00","0,00",NaN,Аптека №6,8,30.09.21,23:25:48,ДокОтгрВх,29720852-bb90-4ce0-8123-63218ccfcd41,NaN,NaN,NaN,"0,00","0,00","0,00","0,00"

In [30]:
df_366=pd.read_csv('/content/366.csv', encoding='1251', delimiter=';')

In [31]:
df_366.head()

,№ п/п,Штрих-код партии,Наименование товара,Поставщик,Дата приходного документа,Номер приходного документа,Дата накладной,Номер накладной,Кол-во,Сумма в закупочных ценах без НДС,Ставка НДС поставщика,Сумма НДС,Сумма в закупочных ценах с НДС
0,1,200200060311,СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. Р.S №100 (50П...,Катрен г.Химки,26.05.2021,2002088.0,25.05.2021,4665120-30,0.040000,33.65,10%,3.37,37.02
1,2,200801594420,КОСМОПОР ПОВЯЗКА 10СМХ6СМ №25 П/ОПЕР. САМОКЛ. ...,Здравсервис,25.03.2020,9000479.8,25.03.2020,E7914339/27806739,0.040000,27.58,10%,2.76,30.34
2,3,200200075091,ХАРТМАНН БРАНОЛИНД H ПОВЯЗКА СТЕР. 10Х20СМ. №3...,Протек,01.09.2021,2003451.0,01.09.2021,164621235-001,0.066667,145.28,10%,14.53,159.81
3,4,200801670938,КОСМОПОР Е ПОВЯЗКА 20СМХ8СМ №25 П/ОПЕР. САМОКЛ...,Протек,17.06.2020,9000628.8,17.06.2020,132215190-001,0.080000,47.07,10%,4.71,51.78
4,5,200801489808,"ФОКУСИН 0,4МГ. №90 КАПС. МОДИФ.ВЫСВ. /ЗЕНТИВА/...",Протек,12.12.2019,9001590.8,12.12.2019,120939343-001,0.111111,96.37,10%,9.64,106.00

In [32]:
df_123=pd.read_csv('/content/А123.csv', encoding='1251', delimiter=';')

In [33]:
df_123.head()

,№ п/п,Штрих-код партии,Наименование товара,Поставщик,Дата приходного документа,Номер приходного документа,Дата накладной,Номер накладной,Кол-во,Сумма в закупочных ценах без НДС,Ставка НДС поставщика,Сумма НДС,Сумма в закупочных ценах с НДС
0,1,201300039533,СФМ ПЕРЧАТКИ СМОТР. ГОЛУБЫЕ Н/СТЕР. НИТРИЛ Р.L...,Катрен г.Химки,19.04.2021,13001265.0,18.04.2021,3541290-30,0.020000,36.48,10%,3.65,40.13
1,2,201300052321,ХАРТМАНН КОСМОПОР Е ПОВЯЗКА 15СМХ8СМ №25 П/ОПЕ...,Фармкомплект ООО,17.08.2021,13002787.0,16.08.2021,ФК003216604,0.040000,18.43,10%,1.84,20.28
2,3,201300053376,"ХАРТМАНН КОСМОПОР Е ПОВЯЗКА 7,2Х5СМ №50 П/ОПЕР...",Здравсервис,26.08.2021,13002938.0,26.08.2021,E12562599/37252019,0.040000,13.06,10%,1.31,14.36
3,4,201300019163,РИНГЕРА Р-Р 200МЛ. №24 Д/ИНФ. /КРАСФАРМА/,Катрен г.Химки,27.10.2020,13001682.0,27.10.2020,8856007-30,0.041667,30.12,10%,3.01,33.14
4,5,201300047442,МААЛОКС 15МЛ. №30 СУСП. Д/ПРИЕМА ВНУТРЬ ПАК.,Пульс,01.07.2021,13002158.0,30.06.2021,БРН00473831,0.066667,47.52,10%,4.75,52.27

In [35]:
df_366.info(), df_123.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5039 entries, 0 to 5038
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   № п/п                             5039 non-null   int64
 1   Штрих-код партии                  5039 non-null   int64
 2   Наименование товара               5039 non-null   object
 3   Поставщик                         5039 non-null   object
 4   Дата приходного документа         5039 non-null   object
 5   Номер приходного документа        5039 non-null   float64
 6   Дата накладной                    5039 non-null   object
 7   Номер накладной                   5029 non-null   object
 8   Кол-во                            5039 non-null   float64
 9   Сумма в закупочных ценах без НДС  5039 non-null   float64
 10  Ставка НДС поставщика             4969 non-null   object
 11  Сумма НДС                         5039 non-null   float64
 12  Сумма в закупочных ценах с НДС    5039 non-null   float64
dtypes: float64(5), int64(2), object(6)
memory usage: 511.9+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4819 entries, 0 to 4818
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   № п/п                             4819 non-null   int64
 1   Штрих-код партии                  4819 non-null   int64
 2   Наименование товара               4819 non-null   object
 3   Поставщик                         4819 non-null   object
 4   Дата приходного документа         4819 non-null   object
 5   Номер приходного документа        4819 non-null   float64
 6   Дата накладной                    4801 non-null   object
 7   Номер накладной                   4784 non-null   object
 8   Кол-во                            4819 non-null   float64
 9   Сумма в закупочных ценах без НДС  4819 non-null   float64
 10  Ставка НДС поставщика             4716 non-null   object
 11  Сумма НДС                         4819 non-null   float64
 12  Сумма в закупочных ценах с НДС    4819 non-null   float64
dtypes: float64(5), int64(2), object(6)
memory usage: 489.6+ KB

(None, None)

In [36]:
result_apteka=pd.concat([df_366, df_123], axis=0)

In [39]:
result_apteka.head()

/usr/local/lib/python3.13/dist-packages/google/colab/_dataframe_summarizer.py:88: UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  cast_date_col = pd.to_datetime(column, errors="coerce")

,№ п/п,Штрих-код партии,Наименование товара,Поставщик,Дата приходного документа,Номер приходного документа,Дата накладной,Номер накладной,Кол-во,Сумма в закупочных ценах без НДС,Ставка НДС поставщика,Сумма НДС,Сумма в закупочных ценах с НДС
0,1,200200060311,СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. Р.S №100 (50П...,Катрен г.Химки,26.05.2021,2002088.0,25.05.2021,4665120-30,0.040000,33.65,10%,3.37,37.02
1,2,200801594420,КОСМОПОР ПОВЯЗКА 10СМХ6СМ №25 П/ОПЕР. САМОКЛ. ...,Здравсервис,25.03.2020,9000479.8,25.03.2020,E7914339/27806739,0.040000,27.58,10%,2.76,30.34
2,3,200200075091,ХАРТМАНН БРАНОЛИНД H ПОВЯЗКА СТЕР. 10Х20СМ. №3...,Протек,01.09.2021,2003451.0,01.09.2021,164621235-001,0.066667,145.28,10%,14.53,159.81
3,4,200801670938,КОСМОПОР Е ПОВЯЗКА 20СМХ8СМ №25 П/ОПЕР. САМОКЛ...,Протек,17.06.2020,9000628.8,17.06.2020,132215190-001,0.080000,47.07,10%,4.71,51.78
4,5,200801489808,"ФОКУСИН 0,4МГ. №90 КАПС. МОДИФ.ВЫСВ. /ЗЕНТИВА/...",Протек,12.12.2019,9001590.8,12.12.2019,120939343-001,0.111111,96.37,10%,9.64,106.00

In [38]:
result_apteka.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9858 entries, 0 to 4818
Data columns (total 13 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   № п/п                             9858 non-null   int64
 1   Штрих-код партии                  9858 non-null   int64
 2   Наименование товара               9858 non-null   object
 3   Поставщик                         9858 non-null   object
 4   Дата приходного документа         9858 non-null   object
 5   Номер приходного документа        9858 non-null   float64
 6   Дата накладной                    9840 non-null   object
 7   Номер накладной                   9813 non-null   object
 8   Кол-во                            9858 non-null   float64
 9   Сумма в закупочных ценах без НДС  9858 non-null   float64
 10  Ставка НДС поставщика             9685 non-null   object
 11  Сумма НДС                         9858 non-null   float64
 12  Сумма в закупочных ценах с НДС    9858 non-null   float64
dtypes: float64(5), int64(2), object(6)
memory usage: 1.3+ MB

In [58]:
WWW['Номер накладной'] = WWW['Номер накладной'].astype(str)

In [59]:
mask = WWW['Поставщик'] == 'ЕАПТЕКА'

In [60]:
WWW.loc[mask, 'Номер накладной'] = WWW.loc[mask, 'Номер накладной'] + '/15'

In [62]:
WWW.tail(25)

,№ п/п,Штрих-код партии,Наименование товара,Поставщик,Дата приходного документа,Номер приходного документа,Дата накладной,Номер накладной,Кол-во,Сумма в закупочных ценах без НДС,Ставка НДС поставщика,Сумма НДС,Сумма в закупочных ценах с НДС
4794,4795,201300055698,"ЦЕФОТАКСИМ 1Г. №1 ПОР. Д/Р-РА Д/В/М,В/В ФЛ. /Д...",Фармкомплект ООО,14.09.2021,13003242.0,13.09.2021,ФК003646506,30.0,612.00,10%,61.20,673.20
4795,4796,201300057178,КОНТЕЙНЕР Д/СБОРА БИОМАТЕРИАЛА 120МЛ. УНИВЕРС....,ГРАНД КАПИТАЛ СМОЛЕНСК ООО ФК,24.09.2021,13003431.0,24.09.2021,21-0-623660,30.0,214.80,10%,21.60,236.40
4796,4797,201300057305,ВАЛИДОЛ 60МГ. №10 ТАБ. ПОДЪЯЗЫЧ. /ФАРМСТАНДАРТ/,Пульс,25.09.2021,13003449.0,24.09.2021,БРН00693055,30.0,897.00,10%,89.70,986.70
4797,4798,201300057638,ПЕРЕКИСЬ ВОДОРОДА 3% 200МЛ. Р-Р ДЕЗ.СР-ВО ФЛ.,Арал плюс,28.09.2021,13003480.0,27.09.2021,8314169,30.0,564.00,20%,112.80,676.80
4798,4799,201300057644,"ХЛОРГЕКСИДИН 0,05% 200МЛ. №1 Р-Р Д/МЕСТ. И НАР...",Арал плюс,28.09.2021,13003480.0,27.09.2021,8314169,30.0,596.40,20%,119.40,715.50
4799,4800,201300057296,ДОКТОР ПЕРЕЦ ЛЕЙКОПЛАСТ. ПЕРЦОВЫЙ 10X18 №1 ПЕР...,Пульс,25.09.2021,13003448.0,24.09.2021,БРН00693054,36.0,974.16,10%,97.56,1071.72
4800,4801,201300050273,"МИКСТУРА ОТ КАШЛЯ СУХАЯ Д/ВЗР. 1,7Г. №1 ПАК. /...",Норман,29.07.2021,13002482.0,27.07.2021,490321,38.0,126.16,10%,12.54,138.70
4801,4802,201300055842,"ЦЕФТРИАКСОН 1Г. №1 ПОР. Д/Р-РА Д/В/В,В/М ФЛ. /...",Пульс,15.09.2021,13003268.0,14.09.2021,БРН00661498,39.0,1197.30,10%,119.73,1317.03
4802,4803,201300046868,"ЛЕЙКОПЛАСТЫРЬ БАКТЕР. 2,5Х7,2 №1 /ВЕРОФАРМ/",ВИТТА КОМПАНИ ООО,25.06.2021,13002091.0,25.06.2021,49294319,40.0,64.00,10%,6.40,70.40
4803,4804,201300057454,"НАФТИЗИН 0,1% 15МЛ. НАЗАЛ.КАПЛИ ФЛ./КАП. /СЛАВ...",Здравсервис,27.09.2021,13003465.0,27.09.2021,E12880997/37877567,43.0,307.88,10%,30.96,338.84
4804,4805,201300056215,ЦЕФАЗОЛИНА НАТРИЕВАЯ СОЛЬ 1Г. №1 ПОР. Д/Р-РА В...,Пульс,17.09.2021,13003317.0,16.09.2021,БРН00668972,49.0,1379.84,10%,138.18,1518.02
4805,4806,200801412675,"Карта LOYALITY 0,01Р","ООО ""Континент""",26.09.2019,8000195.0,08.08.2019,nan,50.0,0.50,NaN,0.00,0.50
4806,4807,201300041030,СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. ОПУДР. Р.L (8...,"ООО ""Акцентмед""",04.05.2021,13001439.0,04.05.2021,ВМ0182914,50.0,844.50,10%,84.50,929.00
4807,4808,201300057810,БОРНАЯ К-ТА 10Г. ДЕЗ.СР-ВО ПОР. (НДС 20%),Арал плюс,30.09.2021,13003522.0,29.09.2021,8316691,50.0,305.50,20%,61.00,366.50
4808,4809,200801670982,ПАКЕТ МАЙКА №1,Подотчетное лицо,17.06.2020,8000402.0,17.06.2020,nan,56.0,95.20,20%,0.00,95.20
4809,4810,200801592399,Карта LOYALITY 25Р,"ООО ""Континент""",24.03.2020,8000113.0,13.03.2020,nan,57.0,799.71,NaN,0.00,799.71
4810,4811,201300014770,СТАКАНЧИК ПЛАСТ. Д/ПРИЕМА ЛЕКАРСТВ 30МЛ.,ВИТТА КОМПАНИ ООО,23.09.2020,13001326.0,23.09.2020,48315698,63.0,157.50,10%,15.75,173.25
4811,4812,201300041031,СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. ОПУДР. Р.M (7...,"ООО ""Акцентмед""",04.05.2021,13001439.0,04.05.2021,ВМ0182914,71.0,1199.19,10%,119.99,1319.18
4812,4813,201300057812,"НАФТИЗИН 0,1% 15МЛ. НАЗАЛ.КАПЛИ ФЛ./КАП. /СЛАВ...",Арал плюс,30.09.2021,13003522.0,29.09.2021,8316691,100.0,676.00,10%,68.00,744.00
4813,4814,201300046887,"ЛЕЙКОПЛАСТЫРЬ БАКТЕР. 2,5Х7,2 №1 /ВЕРОФАРМ/",ГРАНД КАПИТАЛ СМОЛЕНСК ООО ФК,26.06.2021,13002097.0,26.06.2021,21-0-414961,112.0,199.36,10%,20.16,219.52
4814,4815,201300022054,"СФМ ШПРИЦ 10МЛ. 3-Х КОМП. 0,8Х40ММ 21G №1 [SFM]",Арал плюс,17.11.2020,13001962.0,16.11.2020,7998333,117.0,678.60,10%,67.86,746.46
4815,4816,201300046206,ЛЕЙКОПЛАСТЫРЬ БАКТЕР. 4Х10 №1 /ВЕРОФАРМ/,Пульс,19.06.2021,13002022.0,18.06.2021,БРН00443024,124.0,593.96,10%,59.52,653.48
4816,4817,201300048148,ЛЕЙКОПЛАСТЫРЬ БАКТЕР. 6X10 №1 /ВЕРОФАРМ/,Здравсервис,08.07.2021,13002234.0,08.07.2021,E12103072/36238405,125.0,536.25,10%,53.75,590.00
4817,4818,200801680549,ПАКЕТ МАЙКА №1,Подотчетное лицо,27.01.2021,8000018.0,27.01.2021,nan,133.0,226.10,NaN,0.00,226.10
4818,4819,200801680535,ПАКЕТ,Индивидуальный предприниматель Кочанов Андрей ...,18.12.2020,8000532.0,18.12.2020,nan,7633.0,8777.95,NaN,0.00,8777.95

In [63]:
doc_types=['СчФктр', 'УпдДоп', 'УпдСчфДоп', 'ЭДОНакл']
df_t_doc=result[result['Тип документа'].isin(doc_types)].copy()

In [81]:
df_t_doc_cut=df_t_doc[['Номер', 'Сумма', 'Дата']]

In [82]:
df_t_doc_cut.tail()

             Номер      Сумма      Дата
95723     00393491   6 784,13  01.10.18
95726  18-0-971731   3 663,03  01.10.18
95729  18-0-970313   9 861,66  01.10.18
95732  18-0-971380   8 992,66  01.10.18
95735  18-0-970909  14 242,73  01.10.18

In [83]:
df_t_doc_cut['Дата']=pd.to_datetime(df_t_doc_cut['Дата']).dt.strftime('%d.%m.%Y')

/tmp/ipykernel_3868/430276403.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_t_doc_cut['Дата']=pd.to_datetime(df_t_doc_cut['Дата']).dt.strftime('%d.%m.%Y')
/tmp/ipykernel_3868/430276403.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_t_doc_cut['Дата']=pd.to_datetime(df_t_doc_cut['Дата']).dt.strftime('%d.%m.%Y')

In [84]:
df_t_doc_cut.head()

         Номер      Сумма        Дата
0  БРН00709545   4 056,46  30.09.2021
1  БРН00709545   4 056,46  30.09.2021
3  БРН00709520  54 705,65  30.09.2021
4  БРН00709520  54 705,65  30.09.2021
7  БРН00709519   5 890,95  30.09.2021

In [86]:
merged_df=pd.merge(
    result_apteka,
    df_t_doc_cut,
    left_on='Номер накладной',
    right_on='Номер',
    how='left'
)

In [87]:
merged_df.rename(columns={
    'Номер': 'Номер счета-фактуры',
    'Сумма': 'Сумма счет-фактуры',
    'Дата': 'Дата счет-фактуры'
}, inplace=True)

In [88]:
cols = merged_df.columns.tolist()
insert_pos=cols.index('Номер накладной') + 1

In [94]:
for col in ['Номер счета-фактуры', 'Сумма счет-фактуры', 'Дата счет-фактуры']:
  cols.remove(col)

In [95]:
cols.insert(insert_pos, 'Номер счета-фактуры')
cols.insert(insert_pos + 1, 'Сумма счет-фактуры')
cols.insert(insert_pos + 2, 'Дата счет-фактуры')

In [96]:
merged_df=merged_df[cols]

In [99]:
merged_df['Дaтa накладной']=pd.to_datetime(merged_df['Дата накладной'], dayfirst=True, errors='coerce').dt.strftime('%d.%m.%Y')

In [102]:
merged_df=merged_df.loc[:, ~merged_df.columns.duplicated()]

In [103]:
merged_df['Дaтa счет-фактуры']=pd.to_datetime(merged_df['Дата счет-фактуры'], dayfirst=True, errors='coerce').dt.strftime('%d.%m.%Y')

/tmp/ipykernel_3868/1026309031.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['Дaтa счет-фактуры']=pd.to_datetime(merged_df['Дата счет-фактуры'], dayfirst=True, errors='coerce').dt.strftime('%d.%m.%Y')

In [105]:
import numpy as np

In [108]:
merged_df['Сравнение дат']=np.where(
    merged_df['Дaтa счет-фактуры']!=merged_df['Дaтa накладной'],
    'Не совпадает',
    ''
)

/tmp/ipykernel_3868/1709380882.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  merged_df['Сравнение дат']=np.where(

In [109]:
merged_df.head()

,№ п/п,Штрих-код партии,Наименование товара,Поставщик,Дата приходного документа,Номер приходного документа,Дата накладной,Номер накладной,Номер счета-фактуры,Сумма счет-фактуры,Дата счет-фактуры,Кол-во,Сумма в закупочных ценах без НДС,Ставка НДС поставщика,Сумма НДС,Сумма в закупочных ценах с НДС,Дaтa накладной,Дaтa счет-фактуры,Сравнение дат
0,1,200200060311,СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. Р.S №100 (50П...,Катрен г.Химки,26.05.2021,2002088.0,25.05.2021,4665120-30,4665120-30,"16 728,87",25.05.2021,0.040000,33.65,10%,3.37,37.02,25.05.2021,25.05.2021,
1,1,200200060311,СФМ ПЕРЧАТКИ СМОТР. Н/СТЕР. ЛАТ. Р.S №100 (50П...,Катрен г.Химки,26.05.2021,2002088.0,25.05.2021,4665120-30,4665120-30,"16 905,60",25.05.2021,0.040000,33.65,10%,3.37,37.02,25.05.2021,25.05.2021,
2,2,200801594420,КОСМОПОР ПОВЯЗКА 10СМХ6СМ №25 П/ОПЕР. САМОКЛ. ...,Здравсервис,25.03.2020,9000479.8,25.03.2020,E7914339/27806739,E7914339/27806739,"3 395,94",25.03.2020,0.040000,27.58,10%,2.76,30.34,25.03.2020,25.03.2020,
3,3,200200075091,ХАРТМАНН БРАНОЛИНД H ПОВЯЗКА СТЕР. 10Х20СМ. №3...,Протек,01.09.2021,2003451.0,01.09.2021,164621235-001,164621235-001,"13 129,99",09.01.2021,0.066667,145.28,10%,14.53,159.81,01.09.2021,09.01.2021,Не совпадает
4,3,200200075091,ХАРТМАНН БРАНОЛИНД H ПОВЯЗКА СТЕР. 10Х20СМ. №3...,Протек,01.09.2021,2003451.0,01.09.2021,164621235-001,164621235-001,"13 129,99",09.01.2021,0.066667,145.28,10%,14.53,159.81,01.09.2021,09.01.2021,Не совпадает

In [110]:
merged_df.shape

(16527, 19)

In [111]:
pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.13/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.13/dist-packages (from openpyxl) (2.0.0)

In [112]:
merged_df.to_excel('результат.xlsx', index=False)